---
title: "2024.10.BileAcidCode_CleanedCombined"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Setup
library(dplyr)
library(ggplot2)
library(ggbiplot)
library(factoextra)
library(readstata13)
library(sva) #combat!
library(tidyr)
library(vegan)
library(rstatix) #'get summary stats'
library(viridis) #colours for heatmap
library(ggpubr)

knitr::opts_knit$set(root.dir = '/Users/khuus/ownCloud/KH-PhD/BileAcidsManuscript/Manuscript2025')

#functions
source("/Users/khuus/ownCloud/KH-PhD/BileAcidsManuscript/Manuscript2024/kelsey_useful_functions.R")
impute=function(x){
  x[is.na(x)] =min(x, na.rm=TRUE)/2 #convert the NA values to half the minimum from the column, these were 7 initially
  x #display the column
}

```

## Bile Acids Analysis

```{r data preprocessing}

data_bile = readstata13::read.dta13(
  "/Users/khuus/ownCloud/KH-PhD/BileAcidsManuscript/Manuscript2024/BileacidsandmetadataOct20v2.dta", encoding = "latin1" ) %>%
  dplyr::mutate( pays = factor( pays
                                , levels = 1:2
                                , labels = c("Madagascar","CAR"))
                 , Analysisround = factor( Analysisround
                                           , levels = c(1,2,3,4) # correct the mistaken '#4' to '#3'
                                           , labels = c(1,2,3,3) ) 
                 , stunted = factor( stunted
                                     , levels= 1:0
                                     , labels = c("stunted","non-stunted") )
                 # , sexe = factor(sexe, labels = c("Male","Female"), levels = c("Masculin","Féminin"))
                 , sibo = (UFCml >= 200000)
                 , age_years = cut( age
                                    , breaks = c(24, 36, 48, 61)
                                    , labels = c("2-3 years","3-4 years","4-5 years")
                                    , include.lowest = TRUE
                                    , right = TRUE
                                    , dig.lab = 5
                                    , ordered_result = TRUE )
                 , dplyr::across( .cols = c("anemie","sibo","haz","haz2")
                                  ,.fns = as.factor )
  ) %>%
  dplyr::filter( !SampleType %in% c("internalcontrol", "" ) & stunted != "" ) %>%
  dplyr::rename( #Country  = pays,
    calpro = calprotectinelevel
    , aat    = alphaantitrypsinlevel
    , anemia = anemie
    , batch  = Analysisround ) %>%
  #-- removing observations not supposed to exist
  dplyr::filter( !((SampleType == "Duodenal" | SampleType == 'Gastric') & stunted == "non-stunted" ))

###_- then turning to lowercase
colnames(data_bile) = colnames(data_bile) %>%
  tolower() %>%
  gsub("sulfate", "sul", . ) %>%
  gsub("dexy", "deoxy", . ) %>%
  gsub("glucuronide","gluc", .)

#- add a category lithoderivatives
lithoderivatives<-unique(colnames(data_bile)[grep( pattern = "litho", colnames(data_bile))])
lithoderivatives_r<-unique(lithoderivatives[grep( pattern = "_r", lithoderivatives)])
data_bile$lithoderivatives_r = rowSums(data_bile[colnames(data_bile) %in% lithoderivatives_r])

#- add a category urso
urso<-unique(colnames(data_bile)[grep( pattern = "urso", colnames(data_bile))])
urso_r<-unique(urso[grep( pattern = "_r", urso)])
data_bile$urso_r = rowSums(data_bile[colnames(data_bile) %in% urso_r])

#-- fixing column capitalization
colnames(data_bile)[ colnames(data_bile) == "sampletype"] = "SampleType"

#--correct the mistaken 'batch 4' to 'batch 3'
data_bile$batch[which(data_bile$batch==4)] <- 3 

#-- metadata columns
meta_cols = colnames(data_bile)[c( 1:833, 999) ]
Meta      = data_bile %>% dplyr::select( all_of( meta_cols ) ) #take metadata only

#-- bile acid columns
bile_cols = colnames(data_bile)[c( 834:998, 1000:1007) ]
bile_acids      = data_bile %>% dplyr::select( all_of( bile_cols ) ) #take bile acid data only

#--- only the relative abundance columns
acids_rel_abund_col = colnames(data_bile)[ grep(pattern = "_r", colnames(data_bile))]
acids_rel_abund_col <- setdiff(acids_rel_abund_col, meta_cols) #remove accidental metadata
acids_rel_abund = data_bile %>% dplyr::select( all_of( bile_cols ) ) #take rel abundance bile acid data only

#--- only the ratios
acids_ratio_col = colnames(data_bile)[ grep(pattern = "ratio", colnames(data_bile))]
acids_ratio = data_bile %>% dplyr::select( all_of( acids_ratio_col ) ) #take rel abundance bile acid data only

#--- only the grouped as relative abundance
bile_grouped_cols = colnames(data_bile)[c( 990:998, 1006:1007)]
bile_acids_grouped      = data_bile %>% dplyr::select( all_of( bile_grouped_cols ) ) #take bile acid data only

#only the single bile acids, no categories!
single_bile_acids <- setdiff(acids_rel_abund_col, bile_grouped_cols)
single_bile_acids

#--- main tables
X        = data_bile %>% dplyr::select( all_of(c( acids_rel_abund_col, meta_cols ) )) %>%
  group_by(SampleType) %>%
  filter(!duplicated(id)) %>% #for most downstream analyses, remove the technical duplicates
  ungroup()
X_grouped = data_bile %>% dplyr::select( all_of(c( bile_grouped_cols, meta_cols ) ))
X_ratio = data_bile %>% dplyr::select( all_of(c( acids_ratio_col, meta_cols ) ))


X_CAR= dplyr::filter(X, pays == "CAR")
X_Mada= dplyr::filter(X, pays == "Madagascar")

#subsets by sample type
feces  = dplyr::filter(X, SampleType == "Feces")
feces2 = dplyr::filter(feces, haz2!=1) #to compare only NN and MCS

duodenal = dplyr::filter(X, SampleType=="Duodenal")
gastric = dplyr::filter(X, SampleType=="Gastric")

feces_CAR = dplyr::filter(X, (SampleType=="Feces" & pays=="CAR"))
feces2_CAR = dplyr::filter(feces_CAR, haz2!=1) #to compare only NN and MCS
feces_Mada = dplyr::filter(X, (SampleType=="Feces" & pays=="Madagascar"))
feces2_Mada = dplyr::filter(feces_Mada, haz2!=1) #to compare only NN and MCS

duodenal_CAR = dplyr::filter(X, (SampleType=="Duodenal" & pays=="CAR"))
duodenal_Mada = dplyr::filter(X, (SampleType=="Duodenal" & pays=="Madagascar"))
gastric_CAR= dplyr::filter(X, (SampleType=="Gastric" & pays=="CAR"))
gastric_Mada = dplyr::filter(X, (SampleType=="Gastric" & pays=="Madagascar"))

#check sample size by group
length(feces$id)
length(duodenal$id)
length(gastric$id)

#count for flowchart
dplyr::count(feces, pays, stunted)
dplyr::count(duodenal, pays, stunted)
dplyr::count(gastric, pays, stunted)

#are there any samples missing bile acids data entirely? 
bile_acids_nozeroes <- bile_acids
bile_acids[is.na(bile_acids_nozeroes)] <- 0
bile_acids_nozeroes[which(rowSums(bile_acids_nozeroes)==0),] #no they all have something

```

```{r Fig S2 batch effects}
#For quantification and correction of batch effects, please see alternative markdown for now.
```

```{r Fig 1A}
##Fig 1 A-C : Differences in Bile Acids by SampleType
#A: PCoA WITHOUT combat correction
#X = all the bile acids from the full data_bile set.
RelAbundsingle<- X %>% dplyr::select(all_of(single_bile_acids)) #take only the single bile acids

#consider NAs to be zero
# now impute the values which are NA or 0
RelAbundsingle[RelAbundsingle<=0] <- NA # first convert all negative or 0 values in NA
RelAbundsingle=data.frame(apply(RelAbundsingle,2,impute)) #and then impute them as half the minimum value (instead of zero)
dim(RelAbundsingle)
RelAbundsingle_log<-log10(RelAbundsingle)
RelAbundsingle_log<-as.data.frame(RelAbundsingle_log) 

#corresponding metadata 
RelAbundsingle.meta <- X %>% dplyr::select(all_of(meta_cols))

amp.pca.raw <- prcomp(RelAbundsingle_log, scale=TRUE)
summary(amp.pca.raw)
amp.pca.raw$x[1]

eig.val <- get_eigenvalue(amp.pca.raw)
eig.val$variance.percent

RelAbundsingle.meta$SampleType <- factor(RelAbundsingle.meta$SampleType, levels=c("Gastric", "Duodenal", "Feces"))

#pdf("plots/1A_PCA_sampletype_precombatlog.pdf", width=6, height=5)
p <- ggbiplot(amp.pca.raw,ellipse=FALSE,var.axes=FALSE) 
#groups=ft.df.meta$SampleType, show.legend=FALSE)
p <- p + geom_point(aes(fill=RelAbundsingle.meta$SampleType), 
                    shape=21, size=5, colour="black") + 
  ggtitle("Bile Acids") + 
  theme_bw(base_size=16) + 
  labs(fill="Sample Type") + 
  xlab(paste("PC1 (", round(eig.val$variance.percent[1], 1), "%)", sep="")) + 
  ylab(paste("PC2 (", round(eig.val$variance.percent[2], 1), "%)", sep="")) +
  annotate('text', x=0.5, y=-2.5, label=c("p<0.001"))
p
#dev.off()

#pdf("plots/S1B_PCA_batch_precombatlog.pdf", width=6.5, height=4.5)
p1 <- ggbiplot(amp.pca.raw,ellipse=FALSE,var.axes=FALSE) + geom_point(aes(fill=RelAbundsingle.meta$batch), 
                    shape=21, size=5, colour="black") + 
  ggtitle("Bile Acids") + 
  theme_bw(base_size=16) + 
  labs(fill="Batch") + 
  xlab(paste("PC1 (", round(eig.val$variance.percent[1], 1), "%)", sep="")) + 
  ylab(paste("PC2 (", round(eig.val$variance.percent[2], 1), "%)", sep="")) +
  annotate('text', x=0.5, y=-2.5, label=c("p<0.001"))
p1
#dev.off()

#significance by sample type
#adonis(RelAbundsingle_log ~ batch + SampleType, 
#       data = X, method='eu', sqrt.dist = FALSE)

#For a table - summary statistics

#Summary stats - whole dataset
X_grouped %>% get_summary_stats(primarymain_r, type = "median_iqr")
X_grouped %>% get_summary_stats(conjugated_r, type = "median_iqr")
X_grouped %>% get_summary_stats(gluco_r, type = "median_iqr")
X_grouped %>% get_summary_stats(glyco_r, type = "median_iqr")
X_grouped %>% get_summary_stats(sulfo_r, type = "median_iqr")
X_grouped %>% get_summary_stats(tauro_r, type = "median_iqr")
X_grouped %>% get_summary_stats(lithoderivatives_r, type = "median_iqr")

#Summary stats - Gastric
X_groupedGastric<-filter(X_grouped, SampleType=="Gastric")
X_groupedGastric %>% get_summary_stats(primarymain_r, type = "median_iqr")
X_groupedGastric %>% get_summary_stats(conjugated_r, type = "median_iqr")
X_groupedGastric %>% get_summary_stats(gluco_r, type = "median_iqr")
X_groupedGastric %>% get_summary_stats(glyco_r, type = "median_iqr")
X_groupedGastric %>% get_summary_stats(sulfo_r, type = "median_iqr")
X_groupedGastric %>% get_summary_stats(tauro_r, type = "median_iqr")
X_groupedGastric %>% get_summary_stats(lithoderivatives_r, type = "median_iqr")

#Summary stats - duodenal
X_groupedDuodenal<-filter(X_grouped, SampleType=="Duodenal")
X_groupedDuodenal %>% get_summary_stats(primarymain_r, type = "median_iqr")
X_groupedDuodenal %>% get_summary_stats(conjugated_r, type = "median_iqr")
X_groupedDuodenal %>% get_summary_stats(gluco_r, type = "median_iqr")
X_groupedDuodenal %>% get_summary_stats(glyco_r, type = "median_iqr")
X_groupedDuodenal %>% get_summary_stats(sulfo_r, type = "median_iqr")
X_groupedDuodenal %>% get_summary_stats(tauro_r, type = "median_iqr")
X_groupedDuodenal %>% get_summary_stats(lithoderivatives_r, type = "median_iqr")

#Summary stats - feces
X_groupedFeces<-filter(X_grouped, SampleType=="Feces")
X_groupedFeces %>% get_summary_stats(primarymain_r, type = "median_iqr")
X_groupedFeces %>% get_summary_stats(conjugated_r, type = "median_iqr")
X_groupedFeces %>% get_summary_stats(gluco_r, type = "median_iqr")
X_groupedFeces %>% get_summary_stats(glyco_r, type = "median_iqr")
X_groupedFeces %>% get_summary_stats(sulfo_r, type = "median_iqr")
X_groupedFeces %>% get_summary_stats(tauro_r, type = "median_iqr")
X_groupedFeces %>% get_summary_stats(lithoderivatives_r, type = "median_iqr")

```

```{r Fig 1BCD}

#Test for differences by sample type used a repeated wilcoxen with FDR correction.

# All main bile acid caterogies by Sample Type
# First - uncorrected, by check via glm + batch. #Second - on combat corrected dataset itself.
X_grouped$SampleType <- factor(X_grouped$SampleType, levels = c("Gastric", "Duodenal", "Feces"))
X_ratio$SampleType <- factor(X_ratio$SampleType, levels = c("Gastric", "Duodenal", "Feces"))

#Primary bile acids by sample type. Uncorrected values.
one.way <- kruskal.test(primarymain_r ~ SampleType, data = X_grouped)
one.way #highly significant <2e-16 ***

model <- lm(primarymain_r ~ batch + SampleType, data=X_grouped)
summary(model)

#pdf("plots/1C_PrimaryBileAcidsbySampleType.pdf", width=3, height=3)
p <- ggplot(X_grouped, aes(y=primarymain_r, x=SampleType)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
p <- p + theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10)))
p <- p + xlab("Sample Type") + ylab("Relative abundance (%)") + ggtitle("Primary Bile Acids")
p <- p + annotate('segment', x=1, xend=3, y=105, yend=105)
p <- p + annotate('text', label='***', x=2, y=110)
p
#dev.off()

#Secondary bile acids by sample type. Uncorrected values.
one.way <- kruskal.test(secondarymain_r ~ SampleType, data = X_grouped)
one.way #highly significant <2e-16 ***

model <- lm(secondarymain_r ~ batch + SampleType, data=X_grouped)
summary(model)

#pdf("plots/1D_SecondaryBileAcidsbySampleType.pdf", width=3, height=3)
p <- ggplot(X_grouped, aes(y=secondarymain_r, x=SampleType)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
p <- p + theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10)))
p <- p + xlab("Sample Type") + ylab("Relative abundance (%)") + ggtitle("Secondary Bile Acids")
p <- p + annotate('segment', x=1, xend=3, y=105, yend=105)
p <- p + annotate('text', label='***', x=2, y=110)
p
#dev.off()

#Conjugated bile acids
one.way <- kruskal.test(conjugated_r ~ SampleType, data = X_grouped)
one.way #highly significant <2e-16 ***

model <- lm(conjugated_r ~ batch + SampleType, data=X_grouped)
summary(model)

#pdf("plots/1E_ConjugatedBileAcidsbySampleType.pdf", width=3, height=3)
p <- ggplot(X_grouped, aes(y=conjugated_r, x=SampleType)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
p <- p + theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10)))
p <- p + xlab("Sample Type") + ylab("Relative abundance (%)") + ggtitle("Conjugated Bile Acids")
p <- p + annotate('segment', x=1, xend=3, y=105, yend=105)
p <- p + annotate('text', label='***', x=2, y=110)
p
#dev.off()


#Unonjugated bile acids
one.way <- kruskal.test(unconjugated_r ~ SampleType, data = X_grouped)
one.way #highly significant <2e-16 ***

model <- lm(unconjugated_r ~ batch + SampleType, data=X_grouped)
summary(model)

#pdf("plots/1F_UnconjugatedBileAcidsbySampleType.pdf", width=3, height=3)
p <- ggplot(X_grouped, aes(y=unconjugated_r, x=SampleType)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
p <- p + theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10)))
p <- p + xlab("Sample Type") + ylab("Relative abundance (%)") + ggtitle("Unconjugated Bile Acids")
p <- p + annotate('segment', x=1, xend=3, y=105, yend=105)
p <- p + annotate('text', label='***', x=2, y=110)
p
#dev.off()


#make a heatmap of all the single bile acids by sample type.
#first: summarize the mean value of each bile acid per sample type (?)
to_summarize <- X %>% dplyr::select(all_of(single_bile_acids)) #start again with single
to_summarize[is.na(to_summarize)] <- 0 #0 is 0, no NAs
to_summarize$SampleType <- X$SampleType #add back grouping variable
AverageBySampleType <- to_summarize %>% group_by(SampleType) %>% summarize_all(mean)
AverageBySampleType #nice :) 
AverageBySampleType <- AverageBySampleType %>% pivot_longer(cols=c(2:length(names(AverageBySampleType))),
                                                            names_to="Bile_Acid", values_to="Relative_Abundance")
AverageBySampleType #double nice :) 
AverageBySampleType <- AverageBySampleType[order(AverageBySampleType$Relative_Abundance),]
AverageBySampleType$SampleType <- factor(AverageBySampleType$SampleType, levels=c("Gastric", "Duodenal", "Feces"))
top_bile_acids <- AverageBySampleType %>% filter(Relative_Abundance>=1)
pdata <- AverageBySampleType %>% filter(Bile_Acid %in% top_bile_acids$Bile_Acid)
AverageBySampleType_Gastric <- AverageBySampleType %>% filter(SampleType=="Gastric")
pdata$Bile_Acid <- factor(pdata$Bile_Acid, levels=AverageBySampleType_Gastric$Bile_Acid)

#pdf(width=4, height=4, "plots/1B_Heatmap_BileAcidsbySampleType.pdf",)
p <- ggplot(pdata, aes(x=SampleType, y=Bile_Acid, fill=log(Relative_Abundance))) + geom_tile(colour='black')
p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
p <- p + xlab(NULL) + ylab(NULL)
p <- p + scale_fill_viridis()
#p <- p + scale_fill_gradient2(low="dodgerblue3", mid="lightgreen", high="firebrick2")
p <- p + labs(fill="Log Rel. Abund.") + ggtitle("Major Bile Acids")
p
#dev.off()

#and now: test which ones are significantly different by sample type.
#first: do a repeated kruskal-wallis similar to before.
df_kw <- X %>% dplyr::select(all_of(single_bile_acids)) #start again with single bile acids
df_kw[is.na(df_kw)] <- 0 #0 is 0, no NAs

#test each column (apply 2) by sample type
MW.p = apply(df_kw,2,
             function(x) kruskal.test(c(x)~X$SampleType)$p.value)
p.res = data.frame(Bile_Acid=names(df_kw),MW.p)
# Perform multiple comparison correction using a given method of choice
p.res$rel.fdr <- p.adjust(p.res$MW.p, method="fdr")
p.res$bonferroni <- p.adjust(p.res$MW.p, method="bonferroni") 
p.res[order(p.res$bonferroni),]
p.res.hits <- p.res %>% filter(bonferroni<0.05)
dim(p.res.hits)

#and now do that but with linear models so we can adjust for batch.
MW.lm = apply(df_kw,2,
              function(x) summary(lm(c(x)~X$batch + X$SampleType))$coefficients)
MW.lm 
#this technically works but I guess the question is, what do we really want here...
#each column is the list of first the estimate, then std error, then t value, and the last 5 are p-values for X$batch2, X$batch3, X$SampleTypeFeces, X$SampleTypeGastric
#for example, for the first bile acid:
summary(lm(df_kw$allocholic_acid3sul_r~X$batch + X$SampleType))$coefficients
#taking [4,4] gets us the p-value for feces vs duodenum
summary(lm(df_kw$allocholic_acid3sul_r~X$batch + X$SampleType))$coefficients[4,4]
```

```{r Fig 2ABC combat correct BY sample type}
#feces combat correction
#A: PCoA plus combat correction #update: do it on all bile acids, remove grouped ones later
#X = all the bile acids from the full data_bile set.
RelAbundsingle_F <-feces %>% dplyr::select(all_of(acids_rel_abund_col)) #take single bile acids from FECES
#remove bile acids that don't exist in that compartment
RelAbundsingle_F<-RelAbundsingle_F[,!(colSums(RelAbundsingle_F, na.rm=TRUE)==0)]
#save a list of bile acids which are RARE in that compartment, to exclude later (post PCA/combat)
rareF <- RelAbundsingle_F[,which(colSums(RelAbundsingle_F==0)>(length(RelAbundsingle_F$allocholic_acid3sul_r)*0.8))] #less than 20% prevalent i.e. more than 80% zeroes, e.g. more than 748 zeros out of 935
dim(RelAbundsingle_F) #73 bile acids
dim(rareF) #4 rare bile acids that are >80% zeros / <20% prevalent
names(rareF)

# now impute remaining values which are NA or 0
RelAbundsingle_F[RelAbundsingle_F<=0] <- NA # first convert all negative or 0 values in NA
RelAbundsingle_F=data.frame(apply(RelAbundsingle_F,2,impute)) 

#View(RelAbundsingle_F)
dim(RelAbundsingle_F)

RelAbundsingle_F_log<-log10(RelAbundsingle_F)
RelAbundsingle_F_log<-as.data.frame(RelAbundsingle_F_log) 

#add back the metadata for combat
RelAbundsingle_F.meta <- feces %>% dplyr::select(all_of(meta_cols))
combat_input_F <- data.frame(RelAbundsingle_F_log, RelAbundsingle_F.meta)

mod = model.matrix(~pays+as.factor(stunted), data=combat_input_F)
batch=combat_input_F$batch

RelAbundsingle_F_log_t <- as.data.frame(t(RelAbundsingle_F_log)) #transpose it for ComBat

bile_combat_output_F <- ComBat(dat=RelAbundsingle_F_log_t, mod=mod, batch=batch) 
bile_combat_output_F_t <- as.data.frame(t(bile_combat_output_F))

bile_combat_output_F_meta <- data.frame(bile_combat_output_F_t, RelAbundsingle_F.meta)

#before PCA: take only the single bile acids #any_of because some were removed by filtering already
bile_combat_output_F_t_single <- bile_combat_output_F_t %>% dplyr::select(any_of(single_bile_acids))

amp.pca.combat.F <- prcomp(bile_combat_output_F_t_single, scale=TRUE)
summary(amp.pca.combat.F)
amp.pca.combat.F$x[1]

eig.val <- get_eigenvalue(amp.pca.combat.F)
eig.val$variance.percent

RelAbundsingle_F.meta$SampleType <- factor(RelAbundsingle_F.meta$SampleType, 
                                         levels=c("Gastric", "Duodenal", "Feces"))

#pdf("plots/2A_PCA_country_feces_combat.pdf", width=6, height=4)
pf <- ggbiplot(amp.pca.combat.F,ellipse=FALSE,var.axes=FALSE) 
pf <- pf + geom_point(aes(fill=bile_combat_output_F_meta$pays), shape=21, size=5, colour="black") +
  ggtitle("Feces") + 
  theme_bw(base_size=16) + 
  labs(fill="Country") + 
  xlab(paste("PC1 (", round(eig.val$variance.percent[1], 1), "%)", sep="")) + 
  ylab(paste("PC2 (", round(eig.val$variance.percent[2], 1), "%)", sep="")) +
  annotate("text", label=c("p=0.001"), x=-1.25, y=-4)
pf
#dev.off()

#significance by country, feces
#adonis(bile_combat_output_F_t ~ batch + pays, 
#       data = bile_combat_output_F_meta, method='eu', sqrt.dist = FALSE)

#Gastric only. 
RelAbundsingle_G<-gastric %>% dplyr::select(all_of(acids_rel_abund_col))
RelAbundsingle_G<-RelAbundsingle_G[,!(colSums(RelAbundsingle_G, na.rm=TRUE)==0)] #remove all-zero bile acids
#save a list of bile acids which are RARE in that compartment, to exclude later (post PCA/combat)
rareG <- RelAbundsingle_G[,which(colSums(RelAbundsingle_G==0)>(length(RelAbundsingle_G$allocholic_acid3sul_r)*0.8))] #less than 20% prevalent i.e. more than 80% zeroes, e.g. more than 748 zeros out of 935
dim(RelAbundsingle_G) #75 bile acids
dim(rareG) #5 rare bile acids that are >80% zeros / <20% prevalent
names(rareG)

RelAbundsingle_G[RelAbundsingle_G<=0] <- NA # first convert all negative or 0 values in NA
RelAbundsingle_G=data.frame(apply(RelAbundsingle_G,2,impute)) 
dim(RelAbundsingle_G)

RelAbundsingle_G_log<-log10(RelAbundsingle_G)
RelAbundsingle_G_log<-as.data.frame(RelAbundsingle_G_log) 

#add back the metadata for combat
RelAbundsingle_G.meta <- gastric %>% dplyr::select(all_of(meta_cols))
combat_input_G <- data.frame(RelAbundsingle_G_log, RelAbundsingle_G.meta)

mod = model.matrix(~pays, data=combat_input_G)
batch=combat_input_G$batch

RelAbundsingle_G_log_t <- as.data.frame(t(RelAbundsingle_G_log)) #transpose it for ComBat

bile_combat_output_G <- ComBat(dat=RelAbundsingle_G_log_t, mod=mod, batch=batch) 
bile_combat_output_G_t <- as.data.frame(t(bile_combat_output_G))

bile_combat_output_G_meta <- data.frame(bile_combat_output_G_t, RelAbundsingle_G.meta)

#before PCA: take only the single bile acids #any_of because some were removed by filtering already
bile_combat_output_G_t_single <- bile_combat_output_G_t %>% dplyr::select(any_of(single_bile_acids))

amp.pca.combat.G <- prcomp(bile_combat_output_G_t_single, scale=TRUE)
summary(amp.pca.combat.G)
amp.pca.combat.G$x[1]

eig.val <- get_eigenvalue(amp.pca.combat.G)
eig.val$variance.percent

#pdf("plots/2C_PCA_country_gastric_combat.pdf", width=6, height=4)
pg <- ggbiplot(amp.pca.combat.G,ellipse=FALSE,var.axes=FALSE) 
pg <- pg + geom_point(aes(fill=bile_combat_output_G_meta$pays), shape=21, size=5, colour="black") +
  ggtitle("Gastric") + 
  theme_bw(base_size=16) + 
  labs(fill="Country") + 
  xlab(paste("PC1 (", round(eig.val$variance.percent[1], 1), "%)", sep="")) + 
  ylab(paste("PC2 (", round(eig.val$variance.percent[2], 1), "%)", sep="")) +
    annotate("text", label=c("p=0.15"), x=-3.5, y=-1.8)
pg
#dev.off()

#significance by country, gas
#adonis(bile_combat_output_G_t ~ batch + pays, 
#       data = bile_combat_output_G_meta, method='eu', sqrt.dist = FALSE)

#Duodenum only. 
RelAbundsingle_D<-duodenal %>% dplyr::select(all_of(acids_rel_abund_col))
RelAbundsingle_D<-RelAbundsingle_D[,!(colSums(RelAbundsingle_D, na.rm=TRUE)==0)] #remove all-zero bile acids
#save a list of bile acids which are RARE in that compartment, to exclude later (post PCA/combat)
rareD <- RelAbundsingle_G[,which(colSums(RelAbundsingle_G==0)>(length(RelAbundsingle_G$allocholic_acid3sul_r)*0.8))] #less than 20% prevalent i.e. more than 80% zeroes, e.g. more than 748 zeros out of 935
dim(RelAbundsingle_G) #75 bile acids
dim(rareD) #5 rare bile acids that are >80% zeros / <20% prevalent
names(rareD)

RelAbundsingle_D[RelAbundsingle_D<=0] <- NA # first convert all negative or 0 values in NA
RelAbundsingle_D=data.frame(apply(RelAbundsingle_D,2,impute)) 
dim(RelAbundsingle_D)

RelAbundsingle_D_log<-log10(RelAbundsingle_D)
RelAbundsingle_D_log<-as.data.frame(RelAbundsingle_D_log) 

#add back the metadata for combat
RelAbundsingle_D.meta <- duodenal %>% dplyr::select(all_of(meta_cols))
combat_input_D <- data.frame(RelAbundsingle_D_log, RelAbundsingle_D.meta)

mod = model.matrix(~pays, data=combat_input_D)
batch=combat_input_D$batch

RelAbundsingle_D_log_t <- as.data.frame(t(RelAbundsingle_D_log)) #transpose it for ComBat

bile_combat_output_D <- ComBat(dat=RelAbundsingle_D_log_t, mod=mod, batch=batch) 
bile_combat_output_D_t <- as.data.frame(t(bile_combat_output_D))

bile_combat_output_D_meta <- data.frame(bile_combat_output_D_t, RelAbundsingle_D.meta)

#before PCA: take only the single bile acids #any_of because some were removed by filtering already
bile_combat_output_D_t_single <- bile_combat_output_D_t %>% dplyr::select(any_of(single_bile_acids))

amp.pca.combat.D <- prcomp(bile_combat_output_D_t_single, scale=TRUE)
summary(amp.pca.combat.D)
amp.pca.combat.D$x[1]

eig.val <- get_eigenvalue(amp.pca.combat.D)
eig.val$variance.percent

#pdf("plots/1B_PCA_country_duodenum_combat.pdf", width=6, height=4)
pd <- ggbiplot(amp.pca.combat.D,ellipse=FALSE,var.axes=FALSE) 
pd <- pd + geom_point(aes(fill=bile_combat_output_D_meta$pays), shape=21, size=5, colour="black") + 
  ggtitle("Duodenal") + 
  theme_bw(base_size=16) + 
  labs(fill="Country") + 
  xlab(paste("PC1 (", round(eig.val$variance.percent[1], 1), "%)", sep="")) + 
  ylab(paste("PC2 (", round(eig.val$variance.percent[2], 1), "%)", sep="")) +
  annotate("text", label=c("p=0.15"), x=1.9, y=-2)
pd
#dev.off()

#significance by country, duo
#adonis(bile_combat_output_D_t ~ batch + pays, 
#       data = bile_combat_output_D_meta, method='eu', sqrt.dist = FALSE)

# Add coord_fixed() to ensure the aspect ratio is fixed for all plots
pf <- pf + coord_fixed(ratio=1)
pd <- pd + coord_fixed(ratio=1)
pg <- pg + coord_fixed(ratio=1.4) #because it's more rectangular

##arrange the PCAs more nicely in a row of 3
pdf(width=10, height=5, "plots/2ABC_pcas_wpvalues.pdf")
ggarrange(pg, pd, pf, ncol=3, nrow=1, 
          widths=c(1,1,1),
          heights=c(1,1,1),
          common.legend=TRUE, legend='right')
dev.off()

```

```{r testing dataframes}
#first, exclude rare bile acids, post combat correction
df_feces <- bile_combat_output_F_t %>% select(-any_of(names(rareF)))
dim(df_feces) #69 bile acids left
identical(df_feces$allocholic_acid3sul_r, bile_combat_output_F_meta$allocholic_acid3sul_r) #confirm order ok

df_gas <- bile_combat_output_G_t %>% select(-any_of(names(rareG)))
dim(df_gas) #70 bile acids left
identical(df_gas$allocholic_acid3sul_r, bile_combat_output_G_meta$allocholic_acid3sul_r) #confirm order ok

df_duo <- bile_combat_output_D_t %>% select(-any_of(names(rareD)))
dim(df_gas) #70 bile acids left
identical(df_gas$allocholic_acid3sul_r, bile_combat_output_G_meta$allocholic_acid3sul_r) #confirm order ok

#for linear models, non combat
#first, exclude rare bile acids, PRE combat correction but POST log transformation
df_fecesLM <- RelAbundsingle_F_log %>% select(-any_of(names(rareF)))
dim(df_fecesLM) #69 bile acids left
identical(df_fecesLM$allocholic_acid3sul_r, combat_input_F$allocholic_acid3sul_r) #confirm order ok

df_gasLM <- RelAbundsingle_G_log %>% select(-any_of(names(rareG)))
dim(df_gasLM) #70 bile acids left
identical(df_gasLM$allocholic_acid3sul_r, combat_input_G$allocholic_acid3sul_r) #confirm order ok

df_duoLM <- RelAbundsingle_D_log %>% select(-any_of(names(rareD)))
dim(df_duoLM) #70 bile acids left
identical(df_duoLM$allocholic_acid3sul_r, combat_input_D$allocholic_acid3sul_r) #confirm order ok


```

```{r Fig 2 repeated testing by country}

##perform repeated wilcoxen by country within sample type. (combat-adjusted data.)
#feces
MW.p.feces.adj = apply(df_feces,2,
                 function(x) wilcox.test(c(x)~bile_combat_output_F_meta$pays)$p.value)
p.res.adj.f = data.frame(Bile_Acid=names(MW.p.feces.adj),
                         pval=MW.p.feces.adj,
                         SampleType=c("Feces"),
                         Test=c("Wilcoxon_combat"),
                         Outcome=c("Country"))
# Perform multiple comparison correction using a given method of choice
p.res.adj.f$qval <- p.adjust(p.res.adj.f$pval, method="fdr")
p.res.adj.f.hits <- p.res.adj.f %>% filter(qval<0.05)
p.res.adj.f.hits
dim(p.res.adj.f.hits)

#duodenum
MW.p.duo.adj = apply(df_duo,2,
                       function(x) wilcox.test(c(x)~bile_combat_output_D_meta$pays)$p.value)
p.res.adj.d = data.frame(Bile_Acid=names(MW.p.duo.adj),
                         pval=MW.p.duo.adj,
                         SampleType=c("Duodenal"),
                         Test=c("Wilcoxon_combat"),
                          Outcome=c("Country"))
# Perform multiple comparison correction using a given method of choice
p.res.adj.d$qval <- p.adjust(p.res.adj.d$pval, method="fdr")
p.res.adj.d.hits <- p.res.adj.d %>% filter(qval<0.05)
p.res.adj.d.hits
dim(p.res.adj.d.hits)

#gastric
MW.p.gas.adj = apply(df_gas,2,
                     function(x) wilcox.test(c(x)~bile_combat_output_G_meta$pays)$p.value)
p.res.adj.g = data.frame(Bile_Acid=names(MW.p.gas.adj),
                         pval=MW.p.gas.adj,
                         SampleType=c("Gastric"),
                         Test=c("Wilcoxon_combat"),
                          Outcome=c("Country"))
# Perform multiple comparison correction using a given method of choice
p.res.adj.g$qval <- p.adjust(p.res.adj.g$pval, method="fdr")
p.res.adj.g.hits <- p.res.adj.g %>% filter(qval<0.05)
p.res.adj.g.hits
dim(p.res.adj.g.hits)

#LINEAR MODELS with covariates

#Feces.
#for example, for the first bile acid:
summary(lm(allocholic_acid3sul_r~batch + sexe + age + pays, data=combat_input_F))$coefficients
summary(lm(allocholic_acid3sul_r~batch + sexe + age + pays, data=combat_input_F))$coefficients[6,4] #is the p value for country

#alternatively for linear models: use the NON combat corrected data, e.g. rel abund only
#V1: with only basic covariates
MW.lm.F = apply(df_fecesLM,2,
              function(x) summary(lm(c(x)~combat_input_F$batch + 
                                       combat_input_F$sexe + 
                                       combat_input_F$age + 
                                       combat_input_F$pays))$coefficients[6,4])
MW.lm.F #provides adjusted p values for country, per bile acid, in feces.
#add an FDR correct:
MW.lm.F2 <- data.frame(Bile_Acid=names(MW.lm.F), 
                       pval=MW.lm.F, 
                       qval=p.adjust(MW.lm.F, method='fdr'),
                       SampleType=c("Feces"),
                       Test=c("LM"),
                        Outcome=c("Country"))

MW.lm.D = apply(df_duoLM,2,
              function(x) summary(lm(c(x)~combat_input_D$batch + 
                                       combat_input_D$sexe + 
                                       combat_input_D$age + 
                                       combat_input_D$pays))$coefficients[6,4])
MW.lm.D2 <- data.frame(Bile_Acid=names(MW.lm.D), 
                       pval=MW.lm.D, 
                       qval=p.adjust(MW.lm.D, method='fdr'),
                       SampleType=c("Duodenal"),
                       Test="LM",
                        Outcome=c("Country"))


MW.lm.G = apply(df_gas,2,
              function(x) summary(lm(c(x)~bile_combat_output_G_meta$batch + 
                                       bile_combat_output_G_meta$sexe + 
                                       bile_combat_output_G_meta$age + 
                                       bile_combat_output_G_meta$pays))$coefficients[6,4])
MW.lm.G2 <- data.frame(Bile_Acid=names(MW.lm.G), 
                       pval=MW.lm.G, 
                       qval=p.adjust(MW.lm.G, method='fdr'),
                       SampleType=c("Gastric"),
                       Test=c("LM"),
                        Outcome=c("Country"))

#combine the data:
diff_country <- Reduce(full_join, list(MW.lm.F2, MW.lm.D2, MW.lm.G2,
                                                p.res.adj.f, p.res.adj.d, p.res.adj.g))
diff_country
#by country, several bile acids are significant both ways per compartment.

#V2: with additional inflammatory and nutritional covariates
#for example, for the first bile acid:
summary(lm(allocholic_acid3sul_r~batch + sexe + age + 
             haz_cont + calprotectinegg + aatmgg + anemia +
             pays, 
           data=combat_input_F))$coefficients
summary(lm(allocholic_acid3sul_r~batch + sexe + age +
             haz_cont + calprotectinegg + aatmgg + anemia +
             pays, 
           data=combat_input_F))$coefficients[10,4] #is the p value for country

#Feces
MW.lm.F3 = apply(df_fecesLM,2,
              function(x) summary(lm(c(x)~combat_input_F$batch + 
                                       combat_input_F$sexe + 
                                       combat_input_F$age + 
                                       combat_input_F$haz_cont +
                                       combat_input_F$calprotectinegg +
                                       combat_input_F$aatmgg + 
                                       combat_input_F$anemia +
                                       combat_input_F$pays))$coefficients[10,4])
#add an FDR correct:
MW.lm.F4 <- data.frame(Bile_Acid=names(MW.lm.F3), 
                       pval=MW.lm.F3, 
                       qval=p.adjust(MW.lm.F3, method='fdr'),
                       SampleType=c("Feces"),
                       Test=c("LM_covariates"),
                        Outcome=c("Country"))

MW.lm.D3 = apply(df_duoLM,2,
              function(x) summary(lm(c(x)~combat_input_D$batch + 
                                       combat_input_D$sexe + 
                                       combat_input_D$age + 
                                       combat_input_D$haz_cont +
                                       combat_input_D$calprotectinesurliquideduodn +
                                       combat_input_D$aatsurldmgml + 
                                       combat_input_D$anemia +
                                       combat_input_D$pays))$coefficients[10,4])
#add an FDR correct:
MW.lm.D4 <- data.frame(Bile_Acid=names(MW.lm.D3), 
                       pval=MW.lm.D3, 
                       qval=p.adjust(MW.lm.D3, method='fdr'),
                       SampleType=c("Duodenal"),
                       Test=c("LM_covariates"),
                        Outcome=c("Country"))


MW.lm.G3 = apply(df_gas,2,
              function(x) summary(lm(c(x)~bile_combat_output_G_meta$batch + 
                                       bile_combat_output_G_meta$sexe + 
                                       bile_combat_output_G_meta$age + 
                                       combat_input_G$haz_cont +
                                       combat_input_G$calprotectinesurliquideduodn +
                                       combat_input_G$aatsurldmgml + 
                                       combat_input_G$anemia +
                                       bile_combat_output_G_meta$pays))$coefficients[10,4])
#add an FDR correct:
MW.lm.G4 <- data.frame(Bile_Acid=names(MW.lm.G3), 
                       pval=MW.lm.G3, 
                       qval=p.adjust(MW.lm.G3, method='fdr'),
                       SampleType=c("Gastric"),
                       Test=c("LM_covariates"),
                        Outcome=c("Country"))

#combine the data:
diff_country <- Reduce(full_join, list(p.res.adj.f.hits, p.res.adj.d.hits, p.res.adj.g.hits,
                                       MW.lm.F2, MW.lm.D2, MW.lm.G2,
                                       MW.lm.F4, MW.lm.D4, MW.lm.G4))

#also write this one out.
#write.csv(diff_country, "bile_acid_hits_by_country.csv")

```

```{r Fig 2 diff by country plots}

#are there any bile acids different in all three compartments, by wilcoxen?
Reduce(intersect, list(p.res.adj.f.hits$Bile_Acid, p.res.adj.d.hits$Bile_Acid, p.res.adj.g.hits$Bile_Acid))
#glycolithocholic acid?
#does it pass corrections in all?
diff_country %>% filter(Bile_Acid=="glycolithocholic_acid_r"&pval<0.05) 
#only stays sig by all tests in feces

X$SampleType <- factor(X$SampleType, levels=c("Feces", "Duodenal", "Gastric"))
#doesn't look so impressive
#pdf("plots/2#_Glycolithocholic_acid_Country.pdf", width=4, height=3)
p <- ggplot(X, aes(y=log(glycolithocholic_acid_r), x=pays)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0) + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("Country") + 
  ylab("Relative abundance (%)") + 
  ggtitle("Glycolithocholic Acid") + 
  facet_grid(~SampleType)
p
#dev.off()

#SMALL INTESTINE BY COUNTRY:
#and just in the small intestine? #glycohyodeoxycholic acid
si_hits1 <- intersect(p.res.adj.d.hits$Bile_Acid, p.res.adj.g.hits$Bile_Acid)
#do those hits in the small intestine remain significant after linear models, with and without correction?
si_hits2 <- diff_country %>% filter(Test=="LM"&SampleType%in%c("Gastric", "Duodenal")&qval<0.05) 
si_hits3 <- diff_country %>% filter(Test=="LM_covariates"&SampleType%in%c("Gastric", "Duodenal")&pval<0.05) #allow uncorrected for 'checks'
intersect(si_hits1, si_hits2$Bile_Acid) #glycohyodeoxycholic acid is still sig
intersect(si_hits1, si_hits3$Bile_Acid) #and is still raw significant, after anemia and inflammation correction
si_hits_country <- intersect(si_hits1, si_hits3$Bile_Acid) 

#plot glycohyodeoxycholic acid (and glycohyodeoxycholic_acid3sul_r)
#double check actual stats before plotting:
diff_country %>% filter(Bile_Acid=="glycohyodeoxycholic_acid_r"&pval<0.05)
pdata <- X
pdata$SampleType <- factor(pdata$SampleType, levels=c("Feces", "Duodenal", "Gastric"))
#label data
annotation_data <- data.frame(SampleType=c("Feces", "Duodenal", "Gastric"),
                              sig=c("NS", "*", "*"),
                              x=c(1.5, 1.5, 1.5),
                              y=c(-0.5, -0.5, -0.5))
#pdf("plots/2D_Glycohyodeoxycholic_Country.pdf", width=4, height=3)
p <- ggplot(pdata, aes(y=log(glycohyodeoxycholic_acid_r), x=pays)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0) + theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("Country") + ylab("Log relative abundance (%)") + ggtitle("Glycohyodeoxycholic Acid") + 
  facet_grid(~SampleType) + 
  annotate('segment', x=1, xend=2, y=-1, yend=-1) #+
  #annotate('text', x=c(1.5, 1.5, 1.5), y=c(-0.5, -0.5, -0.5),
    #aes(label = sig))
p
#dev.off()

#bile acids which are significant in feces by wilcoxon:
fecal_hits <- p.res.adj.f.hits %>% filter(qval<0.05)
#bile acids which are significant in feces after adjusting for additional covariates:
fecal_hits_corr <- MW.lm.F4 %>% filter(qval<0.05) 
fecal_hits_corr$Bile_Acid
#bile acids which do NOT remain significant after adjusting for additional covariates?
fecal_hits <- MW.lm.F2 %>% filter(qval<0.05)
fecal_hits_lost <- setdiff(fecal_hits$Bile_Acid, fecal_hits_corr$Bile_Acid)
fecal_hits_lost #only a few
#check the main hits by feces that are significant by everything 
feces_hits_country <- Reduce(intersect, list(p.res.adj.f.hits$Bile_Acid,
                                             MW.lm.F2[which(MW.lm.F4$qval<0.05),]$Bile_Acid,
                                             MW.lm.F4[which(MW.lm.F4$qval<0.05),]$Bile_Acid))
feces_hits_country

#since there are so many: first make boxplots for the main categories: primary, tauro, and lithoderivatives

# make boxplots by country of origin
#double check p values for selection 
diff_country %>% filter(Bile_Acid=="primarymain_r"&qval<0.05) #sig by feces all types of model; NS in SI
X$SampleType <- factor(X$SampleType, levels=c("Gastric", "Duodenal", "Feces"))

#add a data frame to label with geom_text()
sigdf <- data.frame(pays=1.5, primarymain_r=115, SampleType=factor("Feces", levels = c("Gastric","Duodenanl","Feces")), label="*")
segdf <- data.frame(pays=c(1,2), primarymain_r=c(105,105), SampleType=factor("Feces", levels = c("Gastric","Duodenanl","Feces")), label="*")


#pdf("plots/2D_PrimaryBileAcidsbyCountryFeces.pdf", width=4.5, height=3)
p <- ggplot(X, aes(y=log(primarymain_r), x=pays)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0) +
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("Country") + ylab("Log relative abundance (%)") + ggtitle("Primary Bile Acids") + 
  facet_grid(~SampleType) +
  geom_text(data = sigdf,label = "*", size=5) +
  geom_line(data=segdf)
p
#dev.off()

#conjugated
diff_country %>% filter(Bile_Acid=="conjugated_r"&qval<0.05) #sig by feces by Wilcoxon and LM only
diff_country %>% filter(Bile_Acid=="conjugated_r"&pval<0.05) #not remotely sig in the adjusted model

#add a data frame to label with geom_text()
sigdf <- data.frame(pays=1.5, conjugated_r=115, SampleType=factor("Feces", levels = c("Gastric","Duodenanl","Feces")), label="*")
segdf <- data.frame(pays=c(1,2), conjugated_r=c(105,105), SampleType=factor("Feces", levels = c("Gastric","Duodenanl","Feces")), label="*")

#pdf("plots/2E_ConjugatedBileAcidsbyCountryFeces.pdf", width=4.5, height=3)
p <- ggplot(X, aes(y=log(conjugated_r), x=pays)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0) +
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("Country") + ylab("Log relative abundance (%)") + ggtitle("Conjugated Bile Acids") + 
  facet_grid(~SampleType) +
    geom_text(data = sigdf,label = "*", size=5) +
  geom_line(data=segdf)
p
#dev.off()

#and now make a heatmap, analagous to the sample-type one but divided by country, for all the consistent hits

#make a heatmap of all the single bile acids by sample type.
#first: summarize the mean value of each bile acid per sample type AND country (?)
to_summarize <- X %>% dplyr::select(all_of(c(p.res.adj.f.hits$Bile_Acid, feces_hits_country, 'SampleType', 'pays'))) #take the hits only
to_summarize[is.na(to_summarize)] <- 0 #0 is 0, no NAs
AverageByCountry <- to_summarize %>% group_by(SampleType, pays) %>% summarize_all(mean)
AverageByCountry #nice :) 
AverageByCountry <- AverageByCountry %>% pivot_longer(cols=c(3:length(names(AverageByCountry))),
                                                            names_to="Bile_Acid", values_to="Relative_Abundance")
AverageByCountry #double nice :) 
AverageByCountry <- AverageByCountry[order(AverageByCountry$Relative_Abundance),]
AverageByCountry$SampleType <- factor(AverageByCountry$SampleType, levels=c("Gastric", "Duodenal", "Feces"))

pdata <- AverageByCountry 
mylevels <- AverageByCountry %>% filter(SampleType=="Feces"&pays=="CAR")
pdata$Bile_Acid <- factor(pdata$Bile_Acid, levels=mylevels$Bile_Acid)

#I think maybe better to plot feces only, right? 
pdata <- pdata %>% filter(SampleType=="Feces" & Bile_Acid %in% c(p.res.adj.f.hits$Bile_Acid))

#scale everything rowwise relative to the average abundance of the bile acid
pdata2 <- pdata %>% group_by(Bile_Acid) %>% mutate(Abund_Avg=mean(Relative_Abundance, na.omit=TRUE))
pdata2$Scaled_Abund <- pdata2$Relative_Abundance / pdata2$Abund_Avg
#add a star in case it is also raw significant in the LMs
lm_stars <- diff_country %>% filter(SampleType=="Feces"&pval<0.05&Test=="LM_covariates")
pdata2$lm_sig <- ifelse(pdata2$pays=="CAR" & #only put the star for one tile
                          pdata2$Bile_Acid %in% lm_stars$Bile_Acid, "*", "")

#pdf(width=6.5, height=3.2, "plots/2F_Heatmap_BileAcidsbyCountry_Feces_Scaled_LMCovstars_v2.pdf",)
p <- ggplot(pdata2, aes(x=pays, y=Bile_Acid, fill=log(Scaled_Abund), label=lm_sig)) + geom_tile(colour='black')
p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  geom_text(colour='white') +
  xlab(NULL) + 
  ylab(NULL) + 
  scale_fill_viridis() + 
  labs(fill="Log Rel. Abund.") + ggtitle("Fecal Bile Acids Differentially Abundant by Country") +
  coord_flip()
p
#dev.off()

```

```{r Fig 3 repeated testing by stunting my way}
##perform repeated spearman by country within sample type. (combat-adjusted data.)
#feces (HAZ)
MS.p.feces.haz = apply(df_feces,2,
                 function(x) cor.test(c(x), bile_combat_output_F_meta$haz_cont, method='spearman')$p.value)
MS.r.feces.haz = apply(df_feces,2,
                 function(x) cor.test(c(x), bile_combat_output_F_meta$haz_cont, method='spearman')$estimate)
p.res.haz.f = data.frame(Bile_Acid=names(MS.p.feces.haz),
                         pval=MS.p.feces.haz,
                         rho=MS.r.feces.haz,
                         SampleType=c("Feces"),
                         Test=c("Spearman_combat"),
                         Outcome=c("HAZ"))
# Perform multiple comparison correction using a given method of choice
p.res.haz.f$qval <- p.adjust(p.res.haz.f$pval, method="fdr")
p.res.haz.f.hits <- p.res.haz.f %>% filter(qval<0.05)
p.res.haz.f.hits[order(p.res.haz.f.hits$pval),] #OK it's ok, with the batch corrected data we still get many lithocholic acid hits
dim(p.res.haz.f.hits)

#feces (Stunted)
MW.p.feces.stunt = apply(df_feces,2,
                 function(x) wilcox.test(c(x)~bile_combat_output_F_meta$stunted)$p.value)
p.res.stunt.f = data.frame(Bile_Acid=names(MW.p.feces.stunt),
                         pval=MW.p.feces.stunt,
                         SampleType=c("Feces"),
                         Test=c("Wilcoxon_combat"))
# Perform multiple comparison correction using a given method of choice
p.res.stunt.f$qval <- p.adjust(p.res.stunt.f$pval, method="fdr")
p.res.stunt.f.hits <- p.res.stunt.f %>% filter(qval<0.05)
p.res.stunt.f.hits
dim(p.res.stunt.f.hits)

#duodenum
MS.p.duo.haz = apply(df_duo,2,
                 function(x) cor.test(c(x), bile_combat_output_D_meta$haz_cont, method='spearman')$p.value)
MS.r.duo.haz = apply(df_duo,2,
                 function(x) cor.test(c(x), bile_combat_output_D_meta$haz_cont, method='spearman')$estimate)
p.res.haz.d = data.frame(Bile_Acid=names(MS.p.duo.haz),
                         pval=MS.p.duo.haz,
                         rho=MS.r.duo.haz,
                         SampleType=c("Duodenal"),
                         Test=c("Spearman_combat"),
                         Outcome=c("HAZ"))
# Perform multiple comparison correction using a given method of choice
p.res.haz.d$qval <- p.adjust(p.res.haz.d$pval, method="fdr")
p.res.haz.d.hits <- p.res.haz.d %>% filter(qval<0.05)
p.res.haz.d.hits #no hits
dim(p.res.haz.d.hits)

#gastric
MS.p.gas.haz = apply(df_gas,2,
                 function(x) cor.test(c(x), bile_combat_output_G_meta$haz_cont, method='spearman')$p.value)
MS.r.gas.haz = apply(df_gas,2,
                 function(x) cor.test(c(x), bile_combat_output_G_meta$haz_cont, method='spearman')$estimate)
p.res.haz.g = data.frame(Bile_Acid=names(MS.p.gas.haz),
                         pval=MS.p.gas.haz,
                         rho=MS.r.gas.haz,
                         SampleType=c("Gastric"),
                         Test=c("Spearman_combat"),
                         Outcome=c("HAZ"))
p.res.haz.g$qval <- p.adjust(p.res.haz.g$pval, method="fdr")
p.res.haz.g.hits <- p.res.haz.g %>% filter(qval<0.05) #no hits
p.res.haz.g.hits
dim(p.res.haz.g.hits)

#LINEAR MODELS, unadjusted data
#Feces.
#for example, for the first bile acid:
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + aatmggdeps + stunted, data=bile_combat_output_F_meta))$coefficients
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + aatmggdeps + stunted, data=bile_combat_output_F_meta))$coefficients[9,4] #is the p value for stunting

lm.F.stunt = apply(df_fecesLM,2,
              function(x) summary(lm(c(x)~bile_combat_output_F_meta$batch + 
                                       bile_combat_output_F_meta$pays +
                                       bile_combat_output_F_meta$sexe + 
                                       bile_combat_output_F_meta$age + 
                                       bile_combat_output_F_meta$calprotectineggdeps +
                                       bile_combat_output_F_meta$aatmggdeps + 
                                       bile_combat_output_F_meta$stunted))$coefficients[9,4])
#add an FDR correct:
lm.F.stunt2 <- data.frame(Bile_Acid=names(lm.F.stunt), 
                       pval=lm.F.stunt, 
                       qval=p.adjust(lm.F.stunt, method='fdr'),
                       SampleType=c("Feces"),
                       Test=c("LM_cov"),
                       Outcome=c("Stunted"))
lm_F_hits <- lm.F.stunt2 %>% filter(qval<0.05)
lm_F_hits #none

#versus HAZ
lm.F.haz = apply(df_fecesLM,2,
              function(x) summary(lm(c(x)~combat_input_F$batch + 
                                       combat_input_F$pays +
                                       combat_input_F$sexe + 
                                       combat_input_F$age + 
                                       combat_input_F$calprotectineggdeps +
                                       combat_input_F$aatmggdeps + 
                                       combat_input_F$haz_cont))$coefficients[9,4])
#add an FDR correct:
lm.F.haz2 <- data.frame(Bile_Acid=names(lm.F.haz), 
                       pval=lm.F.haz, 
                       qval=p.adjust(lm.F.haz, method='fdr'),
                       SampleType=c("Feces"),
                       Test=c("LM_cov"),
                       Outcome=c("HAZ"))
lm_F_hits <- lm.F.haz2 %>% filter(qval<0.05)
lm_F_hits #no hits

#testing: swap order #actually this also works, technically
lm.F.haz_swap = apply(df_fecesLM,2,
              function(x) summary(lm(combat_input_F$haz_cont~combat_input_F$batch + 
                                       combat_input_F$pays +
                                       combat_input_F$sexe + 
                                       combat_input_F$age + 
                                       combat_input_F$calprotectineggdeps +
                                       combat_input_F$aatmggdeps + 
                                       c(x)))$coefficients[9,4])
#add an FDR correct:
lm.F.haz_swap <- data.frame(Bile_Acid=names(lm.F.haz_swap), 
                       pval=lm.F.haz_swap, 
                       qval=p.adjust(lm.F.haz_swap, method='fdr'),
                       SampleType=c("Feces"),
                       Test=c("LM_cov_swapped"),
                       Outcome=c("HAZ"))
lm_F_hits_swap <- lm.F.haz_swap %>% filter(qval<0.05)
lm_F_hits_swap #no hits #but lithoderivatives are near the top, they just don't pass FDR
lm.F.haz_swap[order(lm.F.haz_swap$pval),] %>% filter(pval<0.05)


#Gastric#versus HAZ
lm.G.haz = apply(df_gasLM,2,
              function(x) summary(lm(c(x)~combat_input_G$batch + 
                                       combat_input_G$pays +
                                       combat_input_G$sexe + 
                                       combat_input_G$age + 
                                       combat_input_G$calprotectinesurliquideduodn +
                                       combat_input_G$aatsurldmgml + 
                                       combat_input_G$haz_cont))$coefficients[9,4])
#add an FDR correct:
lm.G.haz2 <- data.frame(Bile_Acid=names(lm.G.haz), 
                       pval=lm.G.haz, 
                       qval=p.adjust(lm.G.haz, method='fdr'),
                       SampleType=c("Gastric"),
                       Test=c("LM_cov"),
                       Outcome=c("HAZ"))

#Duodenum#versus HAZ
lm.D.haz = apply(df_duoLM,2,
              function(x) summary(lm(c(x)~combat_input_D$batch + 
                                       combat_input_D$pays +
                                       combat_input_D$sexe + 
                                       combat_input_D$age + 
                                       combat_input_D$calprotectinesurliquideduodn +
                                       combat_input_D$aatsurldmgml + 
                                       combat_input_D$haz_cont))$coefficients[9,4])
#add an FDR correct:
lm.D.haz2 <- data.frame(Bile_Acid=names(lm.D.haz), 
                       pval=lm.D.haz, 
                       qval=p.adjust(lm.D.haz, method='fdr'),
                       SampleType=c("Duodenal"),
                       Test=c("LM_cov_swapped"),
                       Outcome=c("HAZ"))


#combine the data:
diff_stunting <- Reduce(full_join, list(lm.F.stunt2, lm.F.haz2, lm.F.haz_swap, lm.G.haz2, lm.D.haz2,
                                               p.res.stunt.f, p.res.haz.f, p.res.haz.d, p.res.haz.g))
diff_stunting
View(diff_stunting)

#main hits
diff_stunting[order(diff_stunting$pval),] %>% filter(qval<0.05)
#write them out.
#write.csv(diff_stunting, "/Users/khuus/ownCloud/KH-PhD/BileAcidsManuscript/Manuscript2025/stunting_results_25.01.31.csv")

diff_haz_sig <- diff_stunting %>% filter(qval<0.05)
#so there are no small intestinal hits, that's why I don't have them.

#what about the linear models of the same hits, do they at least remain significant after correction?
diff_stunting %>% filter(SampleType=="Feces" & Bile_Acid %in% diff_haz_sig$Bile_Acid) 
#I mean it's pretty borderline even at raw p value. #but the swapped version for lithoderivatives and HAZ is still sig.
#should I have taken LOG of the bile acids no?

```

```{r extra test}
lm.F.stunt = apply(df_fecesLM,2,
              function(x) summary(lm(c(x)~bile_combat_output_F_meta$batch + 
                                       bile_combat_output_F_meta$sexe + 
                                       bile_combat_output_F_meta$age + 
                                       bile_combat_output_F_meta$calprotectineggdeps +
                                       bile_combat_output_F_meta$aatmggdeps + 
                                       bile_combat_output_F_meta$stunted))$coefficients[c(2:8),4])

lm.F.stunt <- as.data.frame(lm.F.stunt)
lm.F.stunt$Outcome <- sapply(strsplit(row.names(lm.F.stunt), "$", fixed=TRUE),`[`, 2)
lm.F.stunt_corr <- pivot_longer(as.data.frame(lm.F.stunt), cols=c(2:length(names(lm.F.stunt))-1), 
                                                              names_to="Bile_Acid", values_to="pval")
lm.F.stunt_corr
lm.F.stunt_corr$qval <- p.adjust(lm.F.stunt_corr$pval, method='fdr')

#add an FDR correct:
lm.F.stunt2 <- data.frame(Bile_Acid=names(lm.F.stunt), 
                       pval=lm.F.stunt, 
                       qval=p.adjust(lm.F.stunt, method='fdr'),
                       SampleType=c("Feces"),
                       Test=c("LM_cov"),
                       Outcome=c("Stunted"))
lm_F_hits <- lm.F.stunt2 %>% filter(qval<0.05)
lm_F_hits #none

```

```{r Fig 3 stunting plots}
##Fig 3: Differences in Bile Acids by Stunting Status
#reminder main hits:
diff_stunting[order(diff_stunting$pval),] %>% filter(qval<0.05)
feces$stunted <- factor(feces$stunted, levels=c("non-stunted", "stunted"))

#Create plots: Lithoderivatives by stunting status
#pdf("plots/3A_LithoderivativesFecesstunted.pdf", width=4, height=4)
p <- ggplot(feces, aes(y=lithoderivatives_r, x=stunted)) + geom_boxplot(outlier.shape=NA) + 
  geom_jitter(width=0.1, height=0) + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("Stunting") + ylab("Relative abundance (%)") + ggtitle("Lithocholic acid and derivatives") +
  annotate('segment', x=1, xend=2, y=98, yend=98) + annotate('text', label=("***"), x=1.5, y=100)
p
#dev.off()

wilcox.test(lithoderivatives_r ~ stunted, data = X_groupedFeces) #p-value = 0.0008243
one.way <- kruskal.test(lithoderivatives_r ~ haz2, data = X_groupedFeces)
one.way # 0.0013 **

#Lithocholic acid only
#pdf("plots/3#_LithocholicAcid_Fecesstunted.pdf", width=4, height=4)
p <- ggplot(feces, aes(y=lithocholic_acid_r, x=stunted)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0) + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("Stunting") + ylab("Relative abundance (%)") + ggtitle("Lithocholic acid") + 
  annotate('segment', x=1, xend=2, y=98, yend=98) + annotate('text', label=("***"), x=1.5, y=100)
p
#dev.off()
wilcox.test(lithoderivatives_r ~ stunted, data = feces) #p-value = 0.00017

#versus HAZ
#check the spearman stats
diff_stunting %>% filter(Bile_Acid=="lithocholic_acid_r"&qval<0.05)

#pdf("plots/3C_LithocholicAcid_FecesHAZ.pdf", width=4, height=4)
p <- ggplot(feces, aes(y=lithocholic_acid_r, x=haz_cont)) + geom_point() + geom_smooth(method='lm') +
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("HAZ") + ylab("Relative abundance (%)") + ggtitle("Lithocholic acid") +
  annotate("text", x=1.5, y=10, label=c("p=0.003\nrho=0.1"))
p
#dev.off()

#pdf("plots/2D_UrsoFecesstunted.pdf", width=4, height=4)
p <- ggplot(feces, aes(y=urso_r, x=stunted)) + geom_boxplot(outlier.shape=NA) + 
  geom_jitter(width=0.1, height=0) +
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("Stunting") + ylab("Relative abundance (%)") + ggtitle("Ursocholic acid and derivatives") + 
  annotate('segment', x=1, xend=2, y=50, yend=50) + annotate('text', label=("***"), x=1.5, y=52)
p
#dev.off()

wilcox.test(urso_r ~ stunted, data = X_groupedFeces) #p-value = 4.2e-05
one.way <- kruskal.test(urso_r ~ haz2, data = X_groupedFeces)
one.way # 0.0002 **

#pdf("plots/LithoderivativesDuodenumstunted.pdf", width=4, height=4)
p <- ggplot(X_groupedDuodenal, aes(y=lithoderivatives_r, x=haz)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
p <- p + theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10)))
p <- p + xlab("Stunting") + ylab("Relative abundance (%)") + ggtitle("Lithocholic acid and derivatives")
#p <- p + annotate('segment', x=1, xend=2, y=98, yend=98) + annotate('text', label=("***"), x=1.5, y=100)
p
#dev.off()

wilcox.test(lithoderivatives_r ~ haz, data = X_groupedDuodenal) #p-value = 0.78

#pdf("plots/UrsoderivativesDuodenumstunted.pdf", width=4, height=4)
p <- ggplot(X_groupedDuodenal, aes(y=urso_r, x=haz)) + geom_boxplot(outlier.shape=NA) + geom_jitter(width=0.1, height=0)
p <- p + theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10)))
p <- p + xlab("Stunting") + ylab("Relative abundance (%)") + ggtitle("Ursocholic acid and derivatives")
#p <- p + annotate('segment', x=1, xend=2, y=98, yend=98) + annotate('text', label=("***"), x=1.5, y=100)
p
#dev.off()

wilcox.test(urso_r ~ haz, data = X_groupedDuodenal) #p-value = 0.78

#mostly sparse - I would not trust these results because it is so heavily zero skewed.
#pdf("plots/LithocholicAcid24GlucDuodenumHAZ.pdf", width=4, height=4)
p <- ggplot(duodenal, aes(y=lithocholic_acid24gluc_r, x=haz_cont)) + geom_point() + geom_smooth(method='lm')
p <- p + theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10)))
#p <- p + xlab("Stunting") + ylab("Relative abundance (%)") + ggtitle("Lithocholic acid and derivatives")
p
#dev.off()

```

```{r Fig 3E stunting heatmap}
#VISUALIZE the differences by stunting


#make a heatmap of the stunting / HAZ hits that are sig. via spearman's?
#make a heatmap of all the single bile acids by sample type.
#first: summarize the mean value of each bile acid per sample type AND country (?)
to_summarize <- feces %>% dplyr::select(all_of(c(diff_haz_sig$Bile_Acid, 'haz2'))) #take the hits only #from raw data (?) or should I have used combat (?)
to_summarize[is.na(to_summarize)] <- 0 #0 is 0, no NAs
AverageByStunt <- to_summarize %>% dplyr::group_by(as.factor(haz2)) %>% 
  mutate(haz2=as.numeric(haz2)) %>% #because otherwise it complains
  dplyr::summarize_all(mean, na.rm=TRUE) #take 3 categories to visualize
AverageByStunt #nice :) 
AverageByStunt <- AverageByStunt %>% pivot_longer(cols=c(2:length(names(AverageByStunt))),
                                                            names_to="Bile_Acid", values_to="Relative_Abundance")
AverageByStunt #double nice :) 
AverageByStunt <- AverageByStunt[order(AverageByStunt$Relative_Abundance),]

pdata <- AverageByStunt %>% dplyr::rename(haz='as.factor(haz2)')
mylevels <- pdata %>% filter(haz==2)
pdata$Bile_Acid <- factor(pdata$Bile_Acid, levels=mylevels$Bile_Acid)

#sig hits
pdata <- pdata %>% filter(Bile_Acid %in% c(diff_haz_sig$Bile_Acid))

#scale everything rowwise relative to the average abundance of the bile acid
pdata2 <- pdata %>% group_by(Bile_Acid) %>% mutate(Abund_Avg=mean(Relative_Abundance, na.omit=TRUE))
pdata2$Scaled_Abund <- pdata2$Relative_Abundance / pdata2$Abund_Avg
#add a star in case it is also raw significant in the LMs
lm_stars <- diff_stunting %>% filter(SampleType=="Feces"&pval<0.05&Test=="LM_cov")
pdata2$lm_sig <- ifelse(pdata2$haz==3 & #only put the star for one tile
                          pdata2$Bile_Acid %in% lm_stars$Bile_Acid, "*", "")

#pdf(width=6.5, height=3, "plots/3#_Heatmap_BileAcidsbyHAZ_Feces_scaled.pdf",)
p <- ggplot(pdata2, aes(x=as.factor(haz), y=Bile_Acid, fill=Scaled_Abund,label=lm_sig)) + geom_tile(colour='black')
p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  geom_text(colour='white') +
  xlab(NULL) + 
  ylab(NULL) + 
  scale_fill_viridis() + 
  labs(fill="Log Rel. Abund.") + ggtitle("Fecal Bile Acids Differentially Abundant by HAZ") +
  coord_flip()
p
#dev.off()

#alternatively, could do the same heatmap but by stunting instead of HAZ

#first: summarize the mean value of each bile acid per sample type AND country (?)
to_summarize <- feces %>% dplyr::select(all_of(c(diff_haz_sig$Bile_Acid, 'stunted'))) #take the hits only #from raw data (?) or should I have used combat (?)
to_summarize[is.na(to_summarize)] <- 0 #0 is 0, no NAs
AverageByStunt <- to_summarize %>% dplyr::group_by(stunted) %>% 
  dplyr::summarize_all(mean, na.rm=TRUE) #take 3 categories to visualize
AverageByStunt #nice :) 
AverageByStunt <- AverageByStunt %>% pivot_longer(cols=c(2:length(names(AverageByStunt))),
                                                            names_to="Bile_Acid", values_to="Relative_Abundance")
AverageByStunt #double nice :) 
AverageByStunt <- AverageByStunt[order(AverageByStunt$Relative_Abundance),]

pdata <- AverageByStunt 
mylevels <- pdata %>% filter(stunted=='stunted')
pdata$Bile_Acid <- factor(pdata$Bile_Acid, levels=mylevels$Bile_Acid)

#sig hits
pdata <- pdata %>% filter(Bile_Acid %in% c(diff_haz_sig$Bile_Acid))

#scale everything rowwise relative to the average abundance of the bile acid
pdata2 <- pdata %>% group_by(Bile_Acid) %>% mutate(Abund_Avg=mean(Relative_Abundance, na.omit=TRUE))
pdata2$Scaled_Abund <- pdata2$Relative_Abundance / pdata2$Abund_Avg
#add a star in case it is also raw significant in the LMs
lm_stars <- diff_stunting %>% filter(SampleType=="Feces"&pval<0.05&Test=="LM_cov")
pdata2$lm_sig <- ifelse(pdata2$stunted=='stunted' & #only put the star for one tile
                          pdata2$Bile_Acid %in% lm_stars$Bile_Acid, "*", "")

#pdf(width=6.5, height=3, "plots/3#_Heatmap_BileAcidsbyStunt_Feces_scaled.pdf",)
p <- ggplot(pdata2, aes(x=stunted, y=Bile_Acid, fill=Scaled_Abund,label=lm_sig)) + geom_tile(colour='black')
p <- p + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  geom_text(colour='white') +
  xlab(NULL) + 
  ylab(NULL) + 
  scale_fill_viridis() + 
  labs(fill="Log Rel. Abund.") + ggtitle("Fecal Bile Acids Differentially Abundant by Stunting") +
  coord_flip()
p
#dev.off()



```

```{r diff by stunting 2}
##alternatively: for the linear models: use raw input data (table X) exactly like Munir, to compare
dff <- feces %>% dplyr::select(all_of(acids_rel_abund_col))
#for example, for the first bile acid:
summary(lm(allocholic_acid3sul_r~batch + sexe + age + calprotectineggdeps + aatmggdeps + stunted, data=feces))$coefficients
summary(lm(allocholic_acid3sul_r~batch + sexe + age + calprotectineggdeps + aatmggdeps + stunted, data=feces))$coefficients[8,4]
lm.F.stunt_raw = apply(dff,2,
              function(x) summary(lm(c(x)~feces$batch + 
                                       feces$sexe + 
                                       feces$age + 
                                       feces$calprotectineggdeps +
                                       feces$aatmggdeps + 
                                       feces$stunted))$coefficients[8,4])
lm.F.stunt_raw <- data.frame(Bile_Acid=names(lm.F.stunt_raw), 
                       pval_F_stunt=lm.F.stunt_raw, 
                       qval_F_stunt=p.adjust(lm.F.stunt_raw, method='fdr'))

#versus HAZ
lm.F.haz = apply(df_fecesLM,2,
              function(x) summary(lm(c(x)~combat_input_F$batch + 
                                       combat_input_F$sexe + 
                                       combat_input_F$age + 
                                       combat_input_F$calprotectineggdeps +
                                       combat_input_F$aatmggdeps + 
                                       combat_input_F$haz_cont))$coefficients[8,4])
lm.F.haz #provides adjusted p values for country, per bile acid, in feces.
#add an FDR correct:
lm.F.haz2 <- data.frame(Bile_Acid=names(lm.F.haz), 
                       pval_F_haz=lm.F.haz, 
                       qval_F_haz=p.adjust(lm.F.haz, method='fdr'))

```

```{r Fig 4 repeated testing by AAT}
##perform repeated spearman by country within sample type. (combat-adjusted data.)
#feces
MS.p.feces.aat = apply(df_feces,2,
                 function(x) cor.test(c(x), bile_combat_output_F_meta$aatmggdeps, method='spearman')$p.value)
MS.r.feces.aat = apply(df_feces,2,
                 function(x) cor.test(c(x), bile_combat_output_F_meta$aatmggdeps, method='spearman')$estimate)
p.res.aat.f = data.frame(Bile_Acid=names(MS.p.feces.aat),
                         pval=MS.p.feces.aat,
                         rho=MS.r.feces.aat,
                         SampleType=c("Feces"),
                         Test=c("Spearman_combat"),
                         Outcome=c("aatmggdeps"))
# Perform multiple comparison correction using a given method of choice
p.res.aat.f$qval <- p.adjust(p.res.aat.f$pval, method="fdr")
p.res.aat.f.hits <- p.res.aat.f %>% filter(qval<0.05)
p.res.aat.f.hits[order(p.res.aat.f.hits$pval),] #OK it's ok, with the batch corrected data we still get many lithocholic acid hits
dim(p.res.aat.f.hits)

#duodenum
MS.p.duo.aat = apply(df_duo,2,
                 function(x) cor.test(c(x), bile_combat_output_D_meta$aatsurldmgml, method='spearman')$p.value)
MS.r.duo.aat = apply(df_duo,2,
                 function(x) cor.test(c(x), bile_combat_output_D_meta$aatsurldmgml, method='spearman')$estimate)
p.res.aat.d = data.frame(Bile_Acid=names(MS.p.duo.aat),
                         pval=MS.p.duo.aat,
                         rho=MS.r.duo.aat,
                         SampleType=c("Duodenal"),
                         Test=c("Spearman_combat"),
                         Outcome=c("aatsurldmgml"))
# Perform multiple comparison correction using a given method of choice
p.res.aat.d$qval <- p.adjust(p.res.aat.d$pval, method="fdr")
p.res.aat.d.hits <- p.res.aat.d %>% filter(qval<0.05)
p.res.aat.d.hits #no hits
dim(p.res.aat.d.hits)

#gastric
MS.p.gas.aat = apply(df_gas,2,
                 function(x) cor.test(c(x), bile_combat_output_G_meta$aatsurldmgml, method='spearman')$p.value)
MS.r.gas.aat = apply(df_gas,2,
                 function(x) cor.test(c(x), bile_combat_output_G_meta$aatsurldmgml, method='spearman')$estimate)
p.res.aat.g = data.frame(Bile_Acid=names(MS.p.gas.aat),
                         pval=MS.p.gas.aat,
                         rho=MS.r.gas.aat,
                         SampleType=c("Gastric"),
                         Test=c("Spearman_combat"),
                         Outcome=c("aatsurldmgml"))
p.res.aat.g$qval <- p.adjust(p.res.aat.g$pval, method="fdr")
p.res.aat.g.hits <- p.res.aat.g %>% filter(qval<0.05) #no hits
p.res.aat.g.hits
dim(p.res.aat.g.hits)

#LINEAR MODELS, unadjusted data
#Feces.
#for example, for the first bile acid:
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + aatmggdeps, data=bile_combat_output_F_meta))$coefficients
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + aatmggdeps, data=bile_combat_output_F_meta))$coefficients[8,4] #is the p value for stunting

#versus AAT
lm.F.aat = apply(df_fecesLM,2,
              function(x) summary(lm(c(x)~combat_input_F$batch + 
                                       combat_input_F$pays +
                                       combat_input_F$sexe + 
                                       combat_input_F$age + 
                                       combat_input_F$calprotectineggdeps +
                                       combat_input_F$haz_cont +
                                       combat_input_F$aatmggdeps))$coefficients[9,4])
#add an FDR correct:
lm.F.aat2 <- data.frame(Bile_Acid=names(lm.F.aat), 
                       pval=lm.F.aat, 
                       qval=p.adjust(lm.F.aat, method='fdr'),
                       SampleType=c("Feces"),
                       Test=c("LM_cov"),
                       Outcome=c("aatmggdeps"))
lm_F_hits <- lm.F.aat2 %>% filter(qval<0.05)
lm_F_hits #no hits

#Gastric#versus AAT
lm.G.aat = apply(df_gasLM,2,
              function(x) summary(lm(c(x)~combat_input_G$batch + 
                                       combat_input_G$pays +
                                       combat_input_G$sexe + 
                                       combat_input_G$age + 
                                       combat_input_G$calprotectinesurliquideduodn +
                                       combat_input_G$haz_cont +
                                       combat_input_G$aatsurldmgml))$coefficients[9,4])
#add an FDR correct:
lm.G.aat2 <- data.frame(Bile_Acid=names(lm.G.aat), 
                       pval=lm.G.aat, 
                       qval=p.adjust(lm.G.aat, method='fdr'),
                       SampleType=c("Gastric"),
                       Test=c("LM_cov"),
                       Outcome=c("aatsurldmgml"))

#Duodenum#versus AAT
lm.D.aat = apply(df_duoLM,2,
              function(x) summary(lm(c(x)~combat_input_D$batch + 
                                       combat_input_D$pays +
                                       combat_input_D$sexe + 
                                       combat_input_D$age + 
                                       combat_input_D$calprotectinesurliquideduodn +
                                       combat_input_D$haz_cont +
                                       combat_input_D$aatsurldmgml))$coefficients[9,4])
#add an FDR correct:
lm.D.aat2 <- data.frame(Bile_Acid=names(lm.D.aat), 
                       pval=lm.D.aat, 
                       qval=p.adjust(lm.D.aat, method='fdr'),
                       SampleType=c("Duodenal"),
                       Test=c("LM_cov"),
                       Outcome=c("aatsurldmgml"))


#combine the data:
diff_aat <- Reduce(full_join, list(lm.F.aat2, lm.G.aat2, lm.D.aat2,
                                                p.res.aat.f, p.res.aat.d, p.res.aat.g))
diff_aat
View(diff_aat)

#main hits
diff_aat[order(diff_aat$pval),] %>% filter(qval<0.05)
#write them out.
#write.csv(diff_aat, "/Users/khuus/ownCloud/KH-PhD/BileAcidsManuscript/Manuscript2025/AAT_results_plushaz.csv")

diff_aat_sig <- diff_aat %>% filter(qval<0.05)
#so there are no small intestinal hits, that's why I don't have them.

#what about the linear models of the same hits, do they at least remain significant after correction?
diff_aat %>% filter(SampleType=="Feces" & Bile_Acid %in% diff_aat_sig$Bile_Acid) 

#check some of the things Pascale wrote
diff_aat %>% filter(Bile_Acid %in% c("taurochenodeoxycholic_acid_r", "taurocholic_acid_r", "glycocholic_acid_r", 
                                     "glycochenodeoxycholic_acid_r", "cholic_acid_r"))

```

```{r Fig 4 AAT plots}
#plot the main categories: sulfo_r, sumprimarysecondarymain_r, 

#sulfo R versus AAT #best hit, not amazing if you ask me
diff_aat %>% filter(Bile_Acid=="sulfo_r") #plot the spearman's one

#pdf("plots/4D_FecesAAT_sulfo_r.pdf", width=3.5, height=3.5)
p <- ggplot(feces, aes(y=log(sulfo_r), x=log(aatmggdeps))) + geom_point() + geom_smooth(method='lm') + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) +
  xlab("AAT") + ylab("Log Relative abundance") + ggtitle("Sulfated Bile Acids") +
  annotate("text", x=1.25, y=-4, label=c("q=1.3e-08\nrho=0.22"))
p
#dev.off()

#lithoderivatives_r
diff_aat %>% filter(Bile_Acid=="lithoderivatives_r")

#pdf("plots/4D_FecesAAT_lithoderivatives.pdf", width=3.5, height=3.5)
p <- ggplot(feces, aes(y=log(lithoderivatives_r), x=log(aatmggdeps))) + geom_point() + geom_smooth(method='lm') + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) +
  xlab("AAT") + ylab("Log Relative abundance") + ggtitle("Lithocholic Acid Derivatives") +
  annotate("text", x=1.25, y=0, label=c("q=2.3e-06\nrho=-0.14"))
p
#dev.off()

#	secondarymain_r
diff_aat %>% filter(Bile_Acid=="secondarymain_r")

#pdf("plots/4B_FecesAAT_secondarymain.pdf", width=3.5, height=3.5)
p <- ggplot(feces, aes(y=log(secondarymain_r), x=log(aatmggdeps))) + geom_point() + geom_smooth(method='lm') + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) +
    xlab("AAT") + ylab("Log Relative abundance") + ggtitle("Secondary Bile Acids") +
  annotate("text", x=1.25, y=-3, label=c("q=3.5e-04\nrho=-0.14"))
p
#dev.off()

#primarymain_r
diff_aat %>% filter(Bile_Acid=="primarymain_r")

#pdf("plots/4A_FecesAAT_primarymain.pdf", width=3.5, height=3.5)
p <- ggplot(feces, aes(y=log(primarymain_r), x=log(aatmggdeps))) + geom_point() + geom_smooth(method='lm') + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) +
      xlab("AAT") + ylab("Log Relative abundance") + ggtitle("Primary Bile Acids") +
  annotate("text", x=1, y=-2, label=c("q=0.01\nrho=-0.10"))
p
#dev.off()

#sumprimarysecondarymain_r
diff_aat %>% filter(Bile_Acid=="sumprimarysecondarymain_r")

#pdf("plots/4C_FecesAAT_sumprimarysecondarymain.pdf", width=3.5, height=3.5)
p <- ggplot(feces, aes(y=log(sumprimarysecondarymain_r), x=log(aatmggdeps))) + geom_point() + geom_smooth(method='lm') + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) +
      xlab("AAT") + ylab("Log Relative abundance") + ggtitle("Primary & Secondary Bile Acids") +
  annotate("text", x=1.25, y=-2, label=c("q=0.1\nrho=-0.07"))
p
#dev.off()

#instead: plot something else for that category...
diff_aat %>% filter(Test=="Spearman_combat" & SampleType=="Feces" & qval<0.05)

#urso_r
diff_aat %>% filter(Bile_Acid=="urso_r")

pdf("plots/4F_FecesAAT_urso_r.pdf", width=3.5, height=3.5)
p <- ggplot(feces, aes(y=log(urso_r), x=log(aatmggdeps))) + geom_point() + geom_smooth(method='lm') + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) + 
  xlab("AAT") + ylab("Log Relative abundance") + ggtitle("Ursocholic Acid Derivatives") +
  annotate("text", x=1.25, y=-2, label=c("q=7.6e-08\nrho=0.21"))
p
dev.off()


```


```{r Fig 4E AAT heatmap}
#VISUALIZE the differences by stunting


#make a heatmap of the stunting / HAZ hits that are sig. via spearman's?
#make a heatmap of all the single bile acids by sample type.
#first: summarize the mean value of each bile acid per sample type AND country (?)
to_summarize <- feces %>% dplyr::select(all_of(c(diff_aat_sig$Bile_Acid, 'aat'))) #take fecal AAT as binary
to_summarize[is.na(to_summarize)] <- 0 #0 is 0, no NAs
AverageByAAT <- to_summarize %>% dplyr::group_by(aat) %>%
  dplyr::summarize_all(mean, na.rm=TRUE) #take 3 categories to visualize
AverageByAAT #nice :) 
AverageByAAT <- AverageByAAT %>% pivot_longer(cols=c(2:length(names(AverageByAAT))),
                                                            names_to="Bile_Acid", values_to="Relative_Abundance")
AverageByAAT #double nice :) 
AverageByAAT <- AverageByAAT[order(AverageByAAT$Relative_Abundance),]

pdata <- AverageByAAT
mylevels <- pdata %>% filter(aat=="elevated")
pdata$Bile_Acid <- factor(pdata$Bile_Acid, levels=mylevels$Bile_Acid)

#sig hits #and no missing AAT data
pdata <- pdata %>% filter(Bile_Acid %in% c(diff_aat_sig$Bile_Acid) & aat %in% c("normal", "elevated"))

#scale everything rowwise relative to the average abundance of the bile acid
pdata2 <- pdata %>% group_by(Bile_Acid) %>% mutate(Abund_Avg=mean(Relative_Abundance, na.omit=TRUE))
pdata2$Scaled_Abund <- pdata2$Relative_Abundance / pdata2$Abund_Avg
#add a star in case it is also raw significant in the LMs
lm_stars <- diff_aat %>% filter(SampleType=="Feces"&pval<0.05&Test=="LM_cov")
pdata2$lm_sig <- ifelse(pdata2$aat=="elevated" & #only put the star for one tile
                          pdata2$Bile_Acid %in% lm_stars$Bile_Acid, "*", "")

#pdf(width=6.5, height=3.5, "plots/4F_Heatmap_BileAcidsbyAAT_Feces_scaled.pdf",)
p <- ggplot(pdata2, aes(x=aat, y=Bile_Acid, fill=Scaled_Abund,label=lm_sig)) + 
  geom_tile(colour='black') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  geom_text(colour='white') +
  xlab(NULL) + 
  ylab(NULL) + 
  scale_fill_viridis() + 
  labs(fill="Log Rel. Abund.") + ggtitle("Fecal Bile Acids Differentially Abundant by AAT") +
  coord_flip()
p
#dev.off()

```



```{r Fig 4 repeated testing by SIOBO continuous}
##perform repeated spearman by country within sample type. (combat-adjusted data.)
#feces
MS.p.feces.siobo = apply(df_feces,2,
                 function(x) cor.test(c(x), bile_combat_output_F_meta$ufcml, method='spearman')$p.value)
MS.r.feces.siobo = apply(df_feces,2,
                 function(x) cor.test(c(x), bile_combat_output_F_meta$ufcml, method='spearman')$estimate)
p.res.siobo.f = data.frame(Bile_Acid=names(MS.p.feces.siobo),
                         pval=MS.p.feces.siobo,
                         rho=MS.r.feces.siobo,
                         SampleType=c("Feces"),
                         Test=c("Spearman_combat"),
                         Outcome=c("ufcml"))
# Perform multiple comparison correction using a given method of choice
p.res.siobo.f$qval <- p.adjust(p.res.siobo.f$pval, method="fdr")
p.res.siobo.f.hits <- p.res.siobo.f %>% filter(qval<0.05)
p.res.siobo.f.hits[order(p.res.siobo.f.hits$pval),] #only 1: betamuricholic acid

#duodenum
MS.p.duo.siobo = apply(df_duo,2,
                 function(x) cor.test(c(x), bile_combat_output_D_meta$ufcml, method='spearman')$p.value)
MS.r.duo.siobo = apply(df_duo,2,
                 function(x) cor.test(c(x), bile_combat_output_D_meta$ufcml, method='spearman')$estimate)
p.res.siobo.d = data.frame(Bile_Acid=names(MS.p.duo.siobo),
                         pval=MS.p.duo.siobo,
                         rho=MS.r.duo.siobo,
                         SampleType=c("Duodenal"),
                         Test=c("Spearman_combat"),
                         Outcome=c("ufcml"))
# Perform multiple comparison correction using a given method of choice
p.res.siobo.d$qval <- p.adjust(p.res.siobo.d$pval, method="fdr")
p.res.siobo.d.hits <- p.res.siobo.d %>% filter(qval<0.05)
p.res.siobo.d.hits #no hits - aw. I think SI might be different

#gastric
MS.p.gas.siobo = apply(df_gas,2,
                 function(x) cor.test(c(x), bile_combat_output_G_meta$ufcml, method='spearman')$p.value)
MS.r.gas.siobo = apply(df_gas,2,
                 function(x) cor.test(c(x), bile_combat_output_G_meta$ufcml, method='spearman')$estimate)
p.res.siobo.g = data.frame(Bile_Acid=names(MS.p.gas.siobo),
                         pval=MS.p.gas.siobo,
                         rho=MS.r.gas.siobo,
                         SampleType=c("Gastric"),
                         Test=c("Spearman_combat"),
                         Outcome=c("ufcml"))
p.res.siobo.g$qval <- p.adjust(p.res.siobo.g$pval, method="fdr")
p.res.siobo.g.hits <- p.res.siobo.g %>% filter(qval<0.05) #no hits
p.res.siobo.g.hits
dim(p.res.siobo.g.hits) #no hits

#LINEAR MODELS, unadjusted data
#Feces.
#for example, for the first bile acid:
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + ufcml, data=bile_combat_output_F_meta))$coefficients
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + ufcml, data=bile_combat_output_F_meta))$coefficients[8,4] #is the p value for stunting

#versus AAT
lm.F.siobo = apply(df_fecesLM,2,
              function(x) summary(lm(c(x)~combat_input_F$batch + 
                                       combat_input_F$pays +
                                       combat_input_F$sexe + 
                                       combat_input_F$age + 
                                       combat_input_F$calprotectineggdeps +
                                       combat_input_F$haz_cont +
                                       combat_input_F$ufcml))$coefficients[9,4])
#add an FDR correct:
lm.F.siobo2 <- data.frame(Bile_Acid=names(lm.F.siobo), 
                       pval=lm.F.siobo, 
                       qval=p.adjust(lm.F.siobo, method='fdr'),
                       SampleType=c("Feces"),
                       Test=c("LM_cov"),
                       Outcome=c("ufcml"))
lm_F_hits <- lm.F.siobo2 %>% filter(qval<0.05)
lm_F_hits #no hits

#Gastric#versus AAT
lm.G.siobo = apply(df_gasLM,2,
              function(x) summary(lm(c(x)~combat_input_G$batch + 
                                       combat_input_G$pays +
                                       combat_input_G$sexe + 
                                       combat_input_G$age + 
                                       combat_input_G$calprotectinesurliquideduodn +
                                       combat_input_G$haz_cont +
                                       combat_input_G$ufcml))$coefficients[9,4])
#add an FDR correct:
lm.G.siobo2 <- data.frame(Bile_Acid=names(lm.G.siobo), 
                       pval=lm.G.siobo, 
                       qval=p.adjust(lm.G.siobo, method='fdr'),
                       SampleType=c("Gastric"),
                       Test=c("LM_cov"),
                       Outcome=c("ufcml"))

#Duodenum#versus AAT
lm.D.siobo = apply(df_duoLM,2,
              function(x) summary(lm(c(x)~combat_input_D$batch + 
                                       combat_input_D$pays +
                                       combat_input_D$sexe + 
                                       combat_input_D$age + 
                                       combat_input_D$calprotectinesurliquideduodn +
                                       combat_input_D$haz_cont +
                                       combat_input_D$ufcml))$coefficients[9,4])
#add an FDR correct:
lm.D.siobo2 <- data.frame(Bile_Acid=names(lm.D.siobo), 
                       pval=lm.D.siobo, 
                       qval=p.adjust(lm.D.siobo, method='fdr'),
                       SampleType=c("Duodenal"),
                       Test=c("LM_cov"),
                       Outcome=c("ufcml"))


#combine the data:
diff_siobo_cfu <- Reduce(full_join, list(lm.F.siobo2, lm.G.siobo2, lm.D.siobo2,
                                                p.res.siobo.f, p.res.siobo.d, p.res.siobo.g))
diff_siobo_cfu
View(diff_siobo_cfu)

#main hits
diff_siobo_cfu[order(diff_siobo_cfu$pval),] %>% filter(qval<0.05)
#write them out.
#write.csv(diff_siobo, "/Users/khuus/ownCloud/KH-PhD/BileAcidsManuscript/Manuscript2025/SIOBO_results.csv")

diff_siobo_cfu_sig <- diff_siobo_cfu %>% filter(qval<0.05)

#plot the 3 main hits.

```

```{r Fig 4 repeated testing by SIOBO binary}
##perform repeated spearman by country within sample type. (combat-adjusted data.)
#feces
MS.p.feces.siobo = apply(df_feces,2,
                 function(x) wilcox.test(c(x) ~ bile_combat_output_F_meta$sibo)$p.value)
p.res.siobo.f = data.frame(Bile_Acid=names(MS.p.feces.siobo),
                         pval=MS.p.feces.siobo,
                         SampleType=c("Feces"),
                         Test=c("Wilcoxon"),
                         Outcome=c("SIBO"))
# Perform multiple comparison correction using a given method of choice
p.res.siobo.f$qval <- p.adjust(p.res.siobo.f$pval, method="fdr")
p.res.siobo.f.hits <- p.res.siobo.f %>% filter(qval<0.05)
p.res.siobo.f.hits[order(p.res.siobo.f.hits$pval),] #none

#duodenum
MS.p.duo.siobo = apply(df_duo,2,
                 function(x) wilcox.test(c(x) ~ bile_combat_output_D_meta$sibo)$p.value)
p.res.siobo.d = data.frame(Bile_Acid=names(MS.p.duo.siobo),
                         pval=MS.p.duo.siobo,
                         SampleType=c("Duodenal"),
                         Test=c("Spearman_combat"),
                         Outcome=c("SIBO"))
# Perform multiple comparison correction using a given method of choice
p.res.siobo.d$qval <- p.adjust(p.res.siobo.d$pval, method="fdr")
p.res.siobo.d.hits <- p.res.siobo.d %>% filter(qval<0.05)
p.res.siobo.d.hits #no hits - aw. I think SI might be different

#gastric
MS.p.gas.siobo = apply(df_gas,2,
                 function(x) wilcox.test(c(x)~bile_combat_output_G_meta$sibo)$p.value)
p.res.siobo.g = data.frame(Bile_Acid=names(MS.p.gas.siobo),
                         pval=MS.p.gas.siobo,
                         SampleType=c("Gastric"),
                         Test=c("Spearman_combat"),
                         Outcome=c("SIBO"))
p.res.siobo.g$qval <- p.adjust(p.res.siobo.g$pval, method="fdr")
p.res.siobo.g.hits <- p.res.siobo.g %>% filter(qval<0.05) #no hits
p.res.siobo.g.hits
dim(p.res.siobo.g.hits) #no hits

#LINEAR MODELS, unadjusted data
#Feces.
#for example, for the first bile acid:
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + ufcml, data=bile_combat_output_F_meta))$coefficients
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + ufcml, data=bile_combat_output_F_meta))$coefficients[8,4] #is the p value for stunting

#versus AAT
lm.F.siobo = apply(df_fecesLM,2,
              function(x) summary(lm(c(x)~combat_input_F$batch + 
                                       combat_input_F$pays +
                                       combat_input_F$sexe + 
                                       combat_input_F$age + 
                                       combat_input_F$calprotectineggdeps +
                                       combat_input_F$haz_cont +
                                       combat_input_F$sibo))$coefficients[9,4])
#add an FDR correct:
lm.F.siobo2 <- data.frame(Bile_Acid=names(lm.F.siobo), 
                       pval=lm.F.siobo, 
                       qval=p.adjust(lm.F.siobo, method='fdr'),
                       SampleType=c("Feces"),
                       Test=c("LM_cov"),
                       Outcome=c("sibo"))
lm_F_hits <- lm.F.siobo2 %>% filter(qval<0.05)
lm_F_hits #no hits

#Gastric#versus AAT
lm.G.siobo = apply(df_gasLM,2,
              function(x) summary(lm(c(x)~combat_input_G$batch + 
                                       combat_input_G$pays +
                                       combat_input_G$sexe + 
                                       combat_input_G$age + 
                                       combat_input_G$calprotectinesurliquideduodn +
                                       combat_input_G$haz_cont +
                                       combat_input_G$sibo))$coefficients[9,4])
#add an FDR correct:
lm.G.siobo2 <- data.frame(Bile_Acid=names(lm.G.siobo), 
                       pval=lm.G.siobo, 
                       qval=p.adjust(lm.G.siobo, method='fdr'),
                       SampleType=c("Gastric"),
                       Test=c("LM_cov"),
                       Outcome=c("sibo"))

#Duodenum#versus AAT
lm.D.siobo = apply(df_duoLM,2,
              function(x) summary(lm(c(x)~combat_input_D$batch + 
                                       combat_input_D$pays +
                                       combat_input_D$sexe + 
                                       combat_input_D$age + 
                                       combat_input_D$calprotectinesurliquideduodn +
                                       combat_input_D$haz_cont +
                                       combat_input_D$sibo))$coefficients[9,4])
#add an FDR correct:
lm.D.siobo2 <- data.frame(Bile_Acid=names(lm.D.siobo), 
                       pval=lm.D.siobo, 
                       qval=p.adjust(lm.D.siobo, method='fdr'),
                       SampleType=c("Duodenal"),
                       Test=c("LM_cov"),
                       Outcome=c("sibo"))


#combine the data:
diff_siobo <- Reduce(full_join, list(lm.F.siobo2, lm.G.siobo2, lm.D.siobo2,
                                                p.res.siobo.f, p.res.siobo.d, p.res.siobo.g))
diff_siobo
View(diff_siobo)

#main hits
diff_siobo[order(diff_siobo$pval),] %>% filter(qval<0.05)
#write them out.
#write.csv(diff_siobo, "/Users/khuus/ownCloud/KH-PhD/BileAcidsManuscript/Manuscript2025/SIOBO_results.csv")

diff_siobo_sig <- diff_siobo %>% filter(qval<0.05) #nothing

#plot the 3 main hits.

```


```{r Fig 4 repeated testing by hemoglobin continuous}
##perform repeated spearman by country within sample type. (combat-adjusted data.)
#feces
MS.p.feces.haemo = apply(df_feces,2,
                 function(x) cor.test(c(x), bile_combat_output_F_meta$hemoglobine, method='spearman')$p.value)
MS.r.feces.haemo = apply(df_feces,2,
                 function(x) cor.test(c(x), bile_combat_output_F_meta$hemoglobine, method='spearman')$estimate)
p.res.haemo.f = data.frame(Bile_Acid=names(MS.p.feces.haemo),
                         pval=MS.p.feces.haemo,
                         rho=MS.r.feces.haemo,
                         SampleType=c("Feces"),
                         Test=c("Spearman_combat"),
                         Outcome=c("hemoglobine"))
# Perform multiple comparison correction using a given method of choice
p.res.haemo.f$qval <- p.adjust(p.res.haemo.f$pval, method="fdr")
p.res.haemo.f.hits <- p.res.haemo.f %>% filter(qval<0.05)
p.res.haemo.f.hits[order(p.res.haemo.f.hits$pval),] #only 1: betamuricholic acid

#duodenum
MS.p.duo.haemo = apply(df_duo,2,
                 function(x) cor.test(c(x), bile_combat_output_D_meta$hemoglobine, method='spearman')$p.value)
MS.r.duo.haemo = apply(df_duo,2,
                 function(x) cor.test(c(x), bile_combat_output_D_meta$hemoglobine, method='spearman')$estimate)
p.res.haemo.d = data.frame(Bile_Acid=names(MS.p.duo.haemo),
                         pval=MS.p.duo.haemo,
                         rho=MS.r.duo.haemo,
                         SampleType=c("Duodenal"),
                         Test=c("Spearman_combat"),
                         Outcome=c("hemoglobine"))
# Perform multiple comparison correction using a given method of choice
p.res.haemo.d$qval <- p.adjust(p.res.haemo.d$pval, method="fdr")
p.res.haemo.d.hits <- p.res.haemo.d %>% filter(qval<0.05)
p.res.haemo.d.hits #no hits - aw. I think SI might be different

#gastric
MS.p.gas.haemo = apply(df_gas,2,
                 function(x) cor.test(c(x), bile_combat_output_G_meta$hemoglobine, method='spearman')$p.value)
MS.r.gas.haemo = apply(df_gas,2,
                 function(x) cor.test(c(x), bile_combat_output_G_meta$hemoglobine, method='spearman')$estimate)
p.res.haemo.g = data.frame(Bile_Acid=names(MS.p.gas.haemo),
                         pval=MS.p.gas.haemo,
                         rho=MS.r.gas.haemo,
                         SampleType=c("Gastric"),
                         Test=c("Spearman_combat"),
                         Outcome=c("hemoglobine"))
p.res.haemo.g$qval <- p.adjust(p.res.haemo.g$pval, method="fdr")
p.res.haemo.g.hits <- p.res.haemo.g %>% filter(qval<0.05) #no hits
p.res.haemo.g.hits
dim(p.res.haemo.g.hits) #no hits

#LINEAR MODELS, unadjusted data
#Feces.
#for example, for the first bile acid:
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + hemoglobine, data=bile_combat_output_F_meta))$coefficients
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + hemoglobine, data=bile_combat_output_F_meta))$coefficients[8,4] #is the p value for stunting

#versus AAT
lm.F.haemo = apply(df_fecesLM,2,
              function(x) summary(lm(c(x)~combat_input_F$batch + 
                                       combat_input_F$pays +
                                       combat_input_F$sexe + 
                                       combat_input_F$age + 
                                       combat_input_F$calprotectineggdeps +
                                       combat_input_F$haz_cont +
                                       combat_input_F$hemoglobine))$coefficients[9,4])
#add an FDR correct:
lm.F.haemo2 <- data.frame(Bile_Acid=names(lm.F.haemo), 
                       pval=lm.F.haemo, 
                       qval=p.adjust(lm.F.haemo, method='fdr'),
                       SampleType=c("Feces"),
                       Test=c("LM_cov"),
                       Outcome=c("hemoglobine"))
lm_F_hits <- lm.F.haemo2 %>% filter(qval<0.05)
lm_F_hits #no hits

#Gastric#versus AAT
lm.G.haemo = apply(df_gasLM,2,
              function(x) summary(lm(c(x)~combat_input_G$batch + 
                                       combat_input_G$pays +
                                       combat_input_G$sexe + 
                                       combat_input_G$age + 
                                       combat_input_G$calprotectinesurliquideduodn +
                                       combat_input_G$haz_cont +
                                       combat_input_G$hemoglobine))$coefficients[9,4])
#add an FDR correct:
lm.G.haemo2 <- data.frame(Bile_Acid=names(lm.G.haemo), 
                       pval=lm.G.haemo, 
                       qval=p.adjust(lm.G.haemo, method='fdr'),
                       SampleType=c("Gastric"),
                       Test=c("LM_cov"),
                       Outcome=c("hemoglobine"))

#Duodenum#versus AAT
lm.D.haemo = apply(df_duoLM,2,
              function(x) summary(lm(c(x)~combat_input_D$batch + 
                                       combat_input_D$pays +
                                       combat_input_D$sexe + 
                                       combat_input_D$age + 
                                       combat_input_D$calprotectinesurliquideduodn +
                                       combat_input_D$haz_cont +
                                       combat_input_D$hemoglobine))$coefficients[9,4])
#add an FDR correct:
lm.D.haemo2 <- data.frame(Bile_Acid=names(lm.D.haemo), 
                       pval=lm.D.haemo, 
                       qval=p.adjust(lm.D.haemo, method='fdr'),
                       SampleType=c("Duodenal"),
                       Test=c("LM_cov"),
                       Outcome=c("hemoglobine"))


#combine the data:
diff_haemo <- Reduce(full_join, list(lm.F.haemo2, lm.G.haemo2, lm.D.haemo2,
                                                p.res.haemo.f, p.res.haemo.d, p.res.haemo.g))
diff_haemo
View(diff_haemo)

#main hits
diff_haemo[order(diff_haemo$pval),] %>% filter(qval<0.05)
#write them out.
write.csv(diff_haemo, "/Users/khuus/ownCloud/KH-PhD/BileAcidsManuscript/Manuscript2025/haemo_results.csv")

diff_haemo_sig <- diff_haemo %>% filter(qval<0.05)

#what about the linear models of the same hits, do they at least remain significant after correction?
diff_haemo %>% filter(Bile_Acid %in% diff_haemo_sig$Bile_Acid) %>% View()
#no, generally not

```

```{r Fig 4 repeated testing by anaemia binary}
##perform repeated spearman by country within sample type. (combat-adjusted data.)
#feces
MS.p.feces.anaemia = apply(df_feces,2,
                 function(x) wilcox.test(c(x) ~ bile_combat_output_F_meta$anemia)$p.value)
p.res.anaemia.f = data.frame(Bile_Acid=names(MS.p.feces.anaemia),
                         pval=MS.p.feces.anaemia,
                         SampleType=c("Feces"),
                         Test=c("Wilcoxon"),
                         Outcome=c("Anemia"))
# Perform multiple comparison correction using a given method of choice
p.res.anaemia.f$qval <- p.adjust(p.res.anaemia.f$pval, method="fdr")
p.res.anaemia.f.hits <- p.res.anaemia.f %>% filter(qval<0.05)
p.res.anaemia.f.hits[order(p.res.anaemia.f.hits$pval),] #none

#duodenum
MS.p.duo.anaemia = apply(df_duo,2,
                 function(x) wilcox.test(c(x) ~ bile_combat_output_D_meta$anemia)$p.value)
p.res.anaemia.d = data.frame(Bile_Acid=names(MS.p.duo.anaemia),
                         pval=MS.p.duo.anaemia,
                         SampleType=c("Duodenal"),
                         Test=c("Spearman_combat"),
                         Outcome=c("anemia"))
# Perform multiple comparison correction using a given method of choice
p.res.anaemia.d$qval <- p.adjust(p.res.anaemia.d$pval, method="fdr")
p.res.anaemia.d.hits <- p.res.anaemia.d %>% filter(qval<0.05)
p.res.anaemia.d.hits #no hits - aw. I think SI might be different

#gastric
MS.p.gas.anaemia = apply(df_gas,2,
                 function(x) wilcox.test(c(x)~bile_combat_output_G_meta$anemia)$p.value)
p.res.anaemia.g = data.frame(Bile_Acid=names(MS.p.gas.anaemia),
                         pval=MS.p.gas.anaemia,
                         SampleType=c("Gastric"),
                         Test=c("Spearman_combat"),
                         Outcome=c("anemia"))
p.res.anaemia.g$qval <- p.adjust(p.res.anaemia.g$pval, method="fdr")
p.res.anaemia.g.hits <- p.res.anaemia.g %>% filter(qval<0.05) #no hits
p.res.anaemia.g.hits
dim(p.res.anaemia.g.hits) #no hits

#LINEAR MODELS, unadjusted data
#Feces.
#for example, for the first bile acid:
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + hemoglobine, data=bile_combat_output_F_meta))$coefficients
summary(lm(allocholic_acid3sul_r~batch + pays + sexe + age + calprotectineggdeps + hemoglobine, data=bile_combat_output_F_meta))$coefficients[8,4] #is the p value for stunting

#versus AAT
lm.F.anaemia = apply(df_fecesLM,2,
              function(x) summary(lm(c(x)~combat_input_F$batch + 
                                       combat_input_F$pays +
                                       combat_input_F$sexe + 
                                       combat_input_F$age + 
                                       combat_input_F$calprotectineggdeps +
                                       combat_input_F$haz_cont +
                                       combat_input_F$anemia))$coefficients[9,4])
#add an FDR correct:
lm.F.anaemia2 <- data.frame(Bile_Acid=names(lm.F.anaemia), 
                       pval=lm.F.anaemia, 
                       qval=p.adjust(lm.F.anaemia, method='fdr'),
                       SampleType=c("Feces"),
                       Test=c("LM_cov"),
                       Outcome=c("anemia"))
lm_F_hits <- lm.F.anaemia2 %>% filter(qval<0.05)
lm_F_hits #no hits

#Gastric#versus AAT
lm.G.anaemia = apply(df_gasLM,2,
              function(x) summary(lm(c(x)~combat_input_G$batch + 
                                       combat_input_G$pays +
                                       combat_input_G$sexe + 
                                       combat_input_G$age + 
                                       combat_input_G$calprotectinesurliquideduodn +
                                       combat_input_G$haz_cont +
                                       combat_input_G$anemia))$coefficients[9,4])
#add an FDR correct:
lm.G.anaemia2 <- data.frame(Bile_Acid=names(lm.G.anaemia), 
                       pval=lm.G.anaemia, 
                       qval=p.adjust(lm.G.anaemia, method='fdr'),
                       SampleType=c("Gastric"),
                       Test=c("LM_cov"),
                       Outcome=c("anemia"))

#Duodenum#versus AAT
lm.D.anaemia = apply(df_duoLM,2,
              function(x) summary(lm(c(x)~combat_input_D$batch + 
                                       combat_input_D$pays +
                                       combat_input_D$sexe + 
                                       combat_input_D$age + 
                                       combat_input_D$calprotectinesurliquideduodn +
                                       combat_input_D$haz_cont +
                                       combat_input_D$anemia))$coefficients[9,4])
#add an FDR correct:
lm.D.anaemia2 <- data.frame(Bile_Acid=names(lm.D.anaemia), 
                       pval=lm.D.anaemia, 
                       qval=p.adjust(lm.D.anaemia, method='fdr'),
                       SampleType=c("Duodenal"),
                       Test=c("LM_cov"),
                       Outcome=c("anemia"))


#combine the data:
diff_anaemia <- Reduce(full_join, list(lm.F.anaemia2, lm.G.anaemia2, lm.D.anaemia2,
                                                p.res.anaemia.f, p.res.anaemia.d, p.res.anaemia.g))
diff_anaemia
View(diff_anaemia)

#main hits
diff_anaemia[order(diff_anaemia$pval),] %>% filter(qval<0.05)
#write them out.
write.csv(diff_anaemia, "/Users/khuus/ownCloud/KH-PhD/BileAcidsManuscript/Manuscript2025/anaemia_results.csv")

diff_anaemia_sig <- diff_anaemia %>% filter(qval<0.05)

#plot the 3 main hits.

```

```{r haemo & anaemia}
#find hits that are significant for haemoglobine, anaemia, etc.

intersect(diff_haemo_sig$Bile_Acid, diff_anaemia_sig$Bile_Acid)
diff_anaemia$rho <- c("NA")
iron <- rbind(diff_haemo, diff_anaemia)
iron %>% filter(Bile_Acid=="taurodeoxycholic_acid_r")
iron %>% filter(Bile_Acid=="glycohyodeoxycholic_acid_r")
iron %>% filter(Bile_Acid=="omega_muricholic_acid_r")

#anything significant by nonparametric in feces, that is also significant by linear model?
iron %>% filter(Bile_Acid %in% p.res.haemo.f.hits$Bile_Acid) %>% filter(pval<0.05)

```


```{r Fig 4 SIOBO plots}
diff_siobo_sig

#isolithocholic_acid3sul_r
#pdf("plots/4D_FecesAAT_lithoderivatives.pdf", width=3.5, height=3.5)
p <- ggplot(gastric, aes(y=log(isolithocholic_acid3sul_r), x=log(ufcml))) + geom_point() + geom_smooth(method='lm') + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10))) +
  xlab("CFU") + ylab("Log Relative abundance") + ggtitle("Isolithocholic_acid3sul_r") #+
  #annotate("text", x=1.25, y=0, label=c("q=2.3e-06\nrho=-0.14"))
p
#dev.off()

```

```{r haemoglobin plots}

diff_haemo_sig

#taurodeoxycholic_acid_r
#pdf("plots/4D_FecesAAT_lithoderivatives.pdf", width=3.5, height=3.5)
p <- ggplot(feces, aes(y=log(taurodeoxycholic_acid_r), x=log(hemoglobine))) + geom_point() + geom_smooth(method='lm') + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10)))
p
#dev.off()

#taurodeoxycholic_acid_r
#pdf("plots/4D_FecesAAT_lithoderivatives.pdf", width=3.5, height=3.5)
p <- ggplot(feces, aes(y=log(taurodeoxycholic_acid_r), x=log(hemoglobine))) + geom_point() + geom_smooth(method='lm') + 
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black"),
               axis.title.y = element_text(margin = margin(r = 10)))
p
#dev.off()

```

```{r supplementary table}
#combine all statistical outputs into a single table for supplementary file
identical(names(diff_country), names(diff_stunting))

stats_out <- Reduce(full_join, list(diff_country, diff_stunting, diff_aat, diff_siobo))
dim(stats_out)
head(stats_out)

write.csv(stats_out, "Table_SX_allstatresults.csv")

```

```{r Pre-Fig3 multivariate models}
####Pre-figure 2: Multivariate models by stunting/inflammation ####

##KH NOTE - should we first run a filtering step to remove bile acids that are mostly zero in that category??

## Re-grouping analysis

#**Statistical Approach:** In this section, we test to see if there are associations between the bile-acids and outcomes of interest (stunting, SIBO, anemia, etc). We first do Spearman correlation tests (adjusting for p-values). Then we do a linear regression with controls (and interaction effects), and we store the coefficient estimates. Only the main effect p-values has been adjusted using the Benjamin-Hochberg method (e.g. the anemia and pays p-values are uncorrected). 

#We store all of the output in the `corres` object, and we report the associations that are statistically significant (p-value < 0.01) in terms of Spearman *and* linear estimates in the `sig_corr` object. 

#We conduct the following comparisons:

### Comparisons
#  * HAZ-continuous (feces) controlling for batch, age, sex, calprotectine, aat, with interactions with country and anemia
# * HAZ-continuous (duodenal) controlling for batch, age, sex, calprotectine, aat, with interactions with country and anemia
# * UFCml (duodenal)  controlling for batch, age, sex, with interactions with country and anemia
# * UFCml (gastric)  controlling for batch, age, sex, with interactions with country and anemia
# * AAT (feces)  controlling for batch, age, sex, haz_cont, with interactions with country and anemia
# * Calprotectine (feces)  controlling for batch, age, sex, haz_cont, with interactions with country and anemia
# * Hemoglobine (feces)  controlling for batch, age, sex, calprotectine, aat, with interactions with country

acids_ungrouped = c('allocholic_acid3sul_r', 'allocholic_acid_r', 'alloisolithocholic_acid_r'
                    , 'apocholic_acid_r', 'betamuricholic_acid_r', 'chenodeoxycholic_acid_r'
                    , 'chenodeoxycholic_acid24gluc_r', 'chenodeoxycholic_acid3gluc_r'
                    , 'chenodeoxycholic_acid3sul_r', 'cholic_acid_r', 'cholic_acid3sul_r'
                    , 'dehydrocholic_acid_r', 'dehydrolithocholic_acid_r', 'deoxycholic_acid_r'
                    , 'deoxycholic_acid24gluc_r', 'deoxycholic_acid3gluc_r', 'deoxycholic_acid3sul_r'
                    , 'dioxolithocholic_acid_r', 'glycochenodeoxycholic_acid3sul_r', 'glycocholic_acid3sul_r'
                    , 'glycohyodeoxycholic_acid3sul_r', 'glycolithocholic_acid3sul_r', 'glycoallocholic_acid3sul_r'
                    , 'glycoallocholic_acid_r', 'glycochenodeoxycholic_acid_r', 'glycocholic_acid_r'
                    , 'glycodehydrocholic_acid_r', 'glycodeoxycholic_acid_r', 'glycodeoxycholic_acid3sul_r'
                    , 'glycohyocholic_acid_r', 'glycohyodeoxycholic_acid_r', 'glycolithocholic_acid_r'
                    , 'glycoursodeoxycholic_acid_r', 'glycoursodeoxycholic_acid3sul_r', 'hyodeoxycholic_acid_r'
                    , 'isodeoxycholic_acid_r', 'isolithocholic_acid_r', 'isolithocholic_acid3sul_r'
                    , 'lithocholic_acid_r', 'lithocholic_acid24gluc_r', 'lithocholic_acid3gluc_r'
                    , 'lithocholic_acid3sul_r', 'murocholic_acid_r', 'norcholic_acid_r', 'nordeoxycholic_acid_r'
                    , 'norursodeoxycholic_acid_r', 'sevenketodeoxycholic_acid_r', 'sevenketolithocholic_acid_r'
                    , 'sixsevendiketolithocholic_acid_r', 'taurolithocholic_acid3sul_r', 'tauroallocholic_acid_r'
                    , 'tauroamuricholic_acid_r', 'taurobmuricholic_acid_r', 'taurochenodeoxycholic_acid3sul_r'
                    , 'taurochenodeoxycholic_acid_r', 'taurocholic_acid_r', 'taurodehydrocholic_acid_r'
                    , 'taurodeoxycholic_acid_r', 'taurodeoxycholic_acid3sul_r', 'taurohyocholic_acid_r'
                    , 'taurolithocholic_acid_r', 'tauroursodeoxycholic_acid3sul_r', 'taurowmuricholic_acid_r'
                    , 'threeoxocholic_acid_r', 'twelveketocdc_acid_r', 'twelveketolithocholic_acid_r'
                    , 'ursocholic_acid_r', 'ursodeoxycholic_acid_r', 'ursodeoxycholic_acid24gluc_r'
                    , 'ursodeoxycholic_acid3gluc_r', 'ursodeoxycholic_acid3sul_r', 'omega_muricholic_acid_r'
                    , 'lambda_muricholic_acid_r', 'alpha_muricholic_acid_r')

groups = c('urso_r', 'tauro_r', 'glyco_r', 'sulfo_r'
           , 'gluco_r','primarymain_r', 'secondarymain_r', 'lithoderivatives_r')




vars = c( groups)


# vars = acids_ungrouped 

fit_linear = TRUE ### fits a linear model, instead of logistic
corres = NULL
merged = list() 
for ( grouped in c(FALSE, TRUE) ){
  
  #-- either the grouped or ungrouped bile acids
  if (grouped) var_list = vars else var_list = acids_ungrouped 
  
  for (outcome_loop in 1:8 ) {
    if( outcome_loop == 1){ 
      outcome_cont   = "haz_cont"
      outcome_binary = "stunted" 
      comp           = "feces"
      controls       = c( "batch", "age", "sexe", "calprotectineggdeps", "ufcml")
      interactions   = c( "pays", "anemia" )
      #-- do both (and also see if just batch/country )
      # controls       = c( "batch", "age", "sexe", "pays", "calpro", "aat", "anemia")
    }
    if( outcome_loop == 2){ 
      outcome_cont   = "haz_cont"
      outcome_binary = "haz2" 
      comp           = "duodenal"
      controls       = c( "batch", "age", "sexe", "calprotectineggdeps", "aatmggdeps" ) # as markers of EED, later also do a test for association with inflammation in SI
      interactions   = c( "pays", "anemia" )
    }
    if( outcome_loop == 3){ 
      outcome_cont   = "ufcml"
      outcome_binary = "sibo" 
      comp           = "duodenal"
      controls       = c( "batch", "age", "sexe" )
      interactions   = c( "pays", "anemia" )
    }
    if( outcome_loop == 4){ 
      outcome_cont   = "ufcml"
      outcome_binary = "sibo" 
      comp           = "gastric"
      controls       = c( "batch", "age", "sexe" )
      interactions   = c( "pays", "anemia" )
    }
    if( outcome_loop == 5){ 
      outcome_cont   = "aatmggdeps"
      outcome_binary = "aat"
      comp           = "feces"
      controls       = c( "batch", "age", "sexe", "haz_cont") # why not haz_cont here but rather stunted?
      interactions   = c( "pays", "anemia" )
    }
    if( outcome_loop == 6){
      outcome_cont   = "calprotectineggdeps"
      outcome_binary = "calpro"
      comp           = "feces"
      controls       = c( "batch", "age", "sexe", "haz_cont" ) # why not haz_cont here but rather stunted?
      interactions   = c( "pays", "anemia" )
    }
    if(outcome_loop == 7){
      outcome_cont   = "hemoglobine"
      outcome_binary = "anemia"
      comp           = "feces"
      controls       = c( "batch", "age", "sexe"
                          , "calprotectineggdeps", "aatmggdeps", "haz_cont")
      interactions   = "pays"
    }
    
    df = data_bile %>% 
      dplyr::filter( tolower(SampleType) == comp) %>% 
      # dplyr::mutate( age_three = ifelse(age <= 36, "under3","over3")) %>%
      non_missing( controls = c(outcome_cont, outcome_binary, interactions, controls )) %>%
      dplyr::filter( !!sym(outcome_binary) != "" ) %>%
      non_missing( "lithoderivatives_r" )
    
    out = foldchange_logistic_wilcox( df = df
                                      , outcome_binary = outcome_binary
                                      , outcome_cont = outcome_cont
                                      , controls  = controls
                                      , interactions = interactions
                                      , vars = var_list
                                      , name = paste0(comp, "_", outcome_binary)
                                      , fit_linear = fit_linear 
                                      , save_files = FALSE )
    
    temp   = cbind.data.frame( out$corres, comp = comp, outcome_cont = outcome_cont)
    
    #-- in case there are missing columns
    bads = colnames(corres)[ !colnames(corres) %in% colnames(temp)]
    temp[, bads] = NA
    #-- merging 
    corres = rbind.data.frame( corres, temp )
    
    #--- only for the logistic regression code (disabled for now)
    # temp2  = cbind.data.frame( out$merged, comp = comp, outcome_binary = outcome_binary)
    # merged[[ outcome_loop ]]  = temp2 # storing as a list
    
  }# end outcome_loop
}# end grouped/ungrouped 

write.csv( x = corres, file = "correlation_bile_acids_outcomes_test.csv", row.names = FALSE)

## creating the plots THIS DOES NOT WORK FOR THE MOMENT
#-- these are the acids with an adjusted p-value < 0.05 #why both wilcox and linear?
#-- looking at correlation with the continuous outcome (no controls)
sig_corr = corres %>% 
  dplyr::filter(fdr_wilcox < .05 & linear_pval < 0.05 
  ) %>%
  dplyr::select(  outcome_cont, comp, acid, estimate, fdr_wilcox
                  , linear_estimate, linear_pval_adjusted
                  , paysCAR_p.val, anemia1_p.val ) %>%
  tibble::as_tibble()
print(sig_corr, n = Inf)
View(sig_corr)

#--- creating plots 
gg = list()
for( j in 1:nrow(sig_corr)){
  gg[[j]] = ggplot( data_bile %>% 
                      dplyr::filter( tolower(SampleType) == unlist(sig_corr[j, "comp"])  )
                    , aes_string( y = sig_corr[j, "outcome_cont"] %>% unlist()
                                  ,x = sig_corr[j, "acid"] %>% unlist() 
                                  , col = "pays") ) + 
    geom_point( alpha = 0.2 ) +
    geom_smooth(aes_string( y = sig_corr[j, "outcome_cont"] %>% unlist()
                            , x = sig_corr[j, "acid"] %>% unlist() 
                            , fill = "pays"
                            # , method = "lm"
    ), alpha = 0.3 ) +
    # scale_x_continuous( limits = c(0,100))+
    facet_grid(. ~ pays ) +
    labs( subtitle = paste(unlist(sig_corr[j, "comp"]), "samples, correlation =", 
                           signif(unlist(sig_corr[j, "estimate"]),3 ) ) ) + 
    theme_minimal() + 
    theme(legend.position = "none")
}

## printing the output 
print(gg)
# dev.off()

```


