---
title: "Bile acids - Isolates Manuscript"
author: "Simon Yersin"
date: "2025-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading library
```{r}
library(stringr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

# Loading tables
```{r}
isolates <- as.data.frame(read.table("/Users/admin/Documents/VLab_projects/02_Side_projects/SIC_BA_analysis/Tables/summary_bile_acids.tsv",
                            sep = '\t', header = TRUE))

md <- isolates
# Rename columns
colnames(md)[9] <- "Species_name"
colnames(md)[15] <- "Concentrations"
colnames(md)[16] <- "Bile_acids"
colnames(md)[19] <- "Bile_acids_Concentration"
# Clean
md[,19] <- str_remove_all(md[,19], "_ ")


# Filter for isolates of interest:
md <- md %>% filter(Species_name %in% c("Coprococcus comes", "Roseburia intestinalis", "Shigella flexneri", "Fusobacterium mortiferum",
                                    "Campylobacter jejuni jejuni","Lactobacillus salivarius", "Lactobacillus ruminis",
                                    "Streptococcus salivarius", "Granulicatella elegans"))
md <- md %>% filter(Bile_acids %in% c("Glycochenodeoxycholic acid", "Taurochenodeoxycholic acid","Chenodeoxycholic acid",
                                      "Glycolithocholic acid", "Taurolithocholic acid","Lithocholic acid"))

md.levels <- c("Glycolithocholic acid 0.25", "Taurolithocholic acid 0.25","Lithocholic acid 0.5", "Lithocholic acid 0.25",
               "Glycochenodeoxycholic acid 1","Glycochenodeoxycholic acid 0.5","Glycochenodeoxycholic acid 0.25","Taurochenodeoxycholic acid 1",
               "Taurochenodeoxycholic acid 0.5","Taurochenodeoxycholic acid 0.25","Chenodeoxycholic acid 1","Chenodeoxycholic acid 0.5",
               "Chenodeoxycholic acid 0.25")
 
md_dataM <- data.frame(
  Bile_acids_Concentration = md.levels,
  Tacids_num = 1:length(md.levels))
md <- dplyr::left_join(md, md_dataM, by= "Bile_acids_Concentration")

# Rename based on new nomenclature
md$Species_name[which(md$Species_name=="Coprococcus comes")] <- "Bariatricus comes"
md$Species_name[which(md$Species_name=="Lactobacillus salivarius")] <- "Ligilactobacillus salivarius"
md$Species_name[which(md$Species_name=="Lactobacillus ruminis")] <- "Ligilactobacillus ruminis"
```

# Fig 6E
```{r}
fig6E <- ggplot(md, aes(x=Tacids_num, y=AUC, fill = case_when(
                        AUC > 1.1  ~ "#BDD88B",AUC < 0.9  ~ "#E89367",TRUE~ "grey90"))) +
  geom_col() + 
  coord_flip() +
  geom_hline(yintercept=1, alpha = 0.5, linewidth = 0.5) +
  scale_fill_identity() + 
  scale_x_continuous(breaks=1:length(md.levels), labels=md.levels) +
  ggh4x::facet_grid2( ~ factor(Species_name, levels = c("Bariatricus comes", "Roseburia intestinalis", "Shigella flexneri", "Fusobacterium mortiferum",
                                    "Campylobacter jejuni jejuni","Ligilactobacillus salivarius", "Ligilactobacillus ruminis",
                                    "Streptococcus salivarius", "Granulicatella elegans"))) +
  theme_bw(base_size = 10) + 
  theme(text = element_text(family = "Helvetica"),
    strip.text.x = element_text(size = 4, face = "italic", family = "sans"),
        axis.text =  element_text(size = 10, family = "sans"),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 10, family = "sans"),
        panel.border = element_rect(colour = "lightgrey"),
        strip.background = element_blank())
  
pdf("/Users/admin/Documents/VLab_projects/02_Side_projects/SIC_BA_analysis/MS_data_fig_SY/Figure6E.pdf", width = 11, height = 3 )
fig6E
dev.off()
```
# Monocultures
From NA:
Absolute abundance as mean_relAbundOD: relative abundance * OD value / number of bacterial species in the community
Normalized mean_relAbundOD: norm value
```{r}
communities <- as.data.frame(read.csv2("/Users/admin/Documents/VLab_projects/02_Side_projects/SIC_BA_analysis/Tables/combined_data_communities.csv",
                                       sep = ","))
# Bile acid treatment 
unique(communities$Drug)
# "Glycolithocholic Acid", "Taurolithocholic acid", "Lithocholic acid", "Glycochenodeoxycholate", "Taurochenodeoxycholic acid", "Chenodeoxycholic Acid"

# "Unteated 1"                          "Unteated 2"                          "Unteated 3"
mdc <- communities
colnames(mdc)[2] <- "Bile_acid_abbrev"
colnames(mdc)[6] <- "Concentrations"
# Clean captial A
mdc$Drug <- str_replace_all(mdc$Drug, "Acid", "acid")

# Rename Glycochenodeoxycholate for Glycochenodeoxycholic acid
mdc$Drug[which(mdc$Drug == "Glycochenodeoxycholate")] <- "Glycochenodeoxycholic acid"

# Remove " µM" in concentrations
mdc$Concentrations <- str_remove_all(mdc$Concentrations, " µM")

mdc$Concentrations <- as.numeric(mdc$Concentrations)
mdc$Concentrations <- mdc$Concentrations/1000
mdc$Concentrations <- as.character(mdc$Concentrations)
# Add column Bile acids 
mdc <- mdc %>% mutate(Bile_acids_Concentration = str_c(mdc$Drug, " ", mdc$Concentrations))

mdc_norm <- mdc %>% filter(Drug %in% c("Glycochenodeoxycholic acid", "Taurochenodeoxycholic acid","Chenodeoxycholic acid",
                                      "Glycolithocholic acid", "Taurolithocholic acid","Lithocholic acid", "Unteated 1"))
mdc_norm <- mdc_norm[,c(1,4,5,6,7,10)]

# Mulitply rel abundance by 100
mdc_norm$mean_Relabund <- as.numeric(mdc_norm$mean_Relabund)
mdc_norm$mean_Relabund <- mdc_norm$mean_Relabund*100

control_mdc <- mdc_norm %>%
  filter(Drug == "Unteated 1") %>%
  select(Species, Control_RelAbundance = mean_Relabund)

mdc_norm <- mdc_norm %>%
  filter(Drug != "Unteated 1") %>%  # Keep only treated data
  left_join(control_mdc, by = "Species")  # Add control values

mdc_norm <- mdc_norm %>%
  mutate(RelAbun_Baseline = mean_Relabund - Control_RelAbundance)

mdc_norm <- mdc_norm %>%
  mutate(
    # Apply log2 fold change transformation, adding a small constant to avoid log(0)
    Log2FC = log2((mean_Relabund + 0.001014194) / (Control_RelAbundance + 0.001014194)))


# Missing "Chenodeoxycholic acid 1"
mdc.levels <- c("Glycolithocholic acid 0.25", "Taurolithocholic acid 0.25","Lithocholic acid 0.5", "Lithocholic acid 0.25",
               "Glycochenodeoxycholic acid 1","Glycochenodeoxycholic acid 0.5","Glycochenodeoxycholic acid 0.25","Taurochenodeoxycholic acid 1",
               "Taurochenodeoxycholic acid 0.5","Taurochenodeoxycholic acid 0.25","Chenodeoxycholic acid 0.5",
               "Chenodeoxycholic acid 0.25")

mdc_dataM <- data.frame(
  Bile_acids_Concentration = mdc.levels,
  Tacids_num = 1:length(mdc.levels))
mdc_norm <- dplyr::left_join(mdc_norm, mdc_dataM, by= "Bile_acids_Concentration")
unique(mdc_norm$Species)
```

# Fig 6 F
```{r}
mdc_norm <- mdc_norm %>%
  mutate(Species = gsub(" ", "\n", Species))

write.csv(mdc_norm, "/Users/admin/Documents/VLab_projects/02_Side_projects/SIC_BA_analysis/MS_data_fig_SY/TableS6_SynCom_BA.csv", row.names = TRUE)
fig6F <- ggplot(mdc_norm, aes(x=Tacids_num, y=Log2FC, fill = case_when(
                                                          RelAbun_Baseline > 0 ~ "#BDD88B",RelAbun_Baseline < 0  ~ "#E89367",TRUE~ "grey90"))) +
  geom_col() +
  coord_flip() +
  geom_hline(yintercept=0, alpha = 0.5, linewidth = 0.5) +
  scale_fill_identity() + 
  scale_x_continuous(breaks=1:length(mdc.levels), labels=mdc.levels) +
  ggh4x::facet_grid2( ~ factor(Species, levels = c("Agathobacter\nrectalis", "Bariatricus\ncomes", "Bacteroides\novatus",
                                                   "Roseburia\nintestinalis",
                                                        "Anaerostipes\ncaccae", "Anaerobutyricum\nhallii",
                                                        "Shigella\nflexneri","Fusobacterium\nnucleatum","Fusobacterium\nmortiferum",
                                                   "Fusobacterium\nperiodonticum",
                                                        "Limosilactobacillus\nmucosae", "Ligilactobacillus\nsalivarius",
                                                   "Ligilactobacillus\nruminis",
                                                        "Streptococcus\nparasanguinis",
                                                   "Streptococcus\nsalivarius","Granulicatella\nadiacens",  
                                                         "Pseudoleptotrichia\ngoodfellowii",
                                                        "Porphyromonas\nasaccharolytica", "Prevotella\nmelaninogenica",
                                                   "Veillonella\natypica"))) +
  theme_bw(base_size = 12) + 
  theme(text = element_text(family = "Helvetica"),
        strip.text.x = element_text(size = 12, face = "italic", family = "sans"),
        axis.text =  element_text(size = 12, family = "sans"),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size = 12, family = "sans"),
        panel.border = element_rect(colour = "lightgrey"),
        strip.background = element_blank())


pdf("/Users/admin/Documents/VLab_projects/02_Side_projects/SIC_BA_analysis/MS_data_fig_SY/Figure6F.pdf", width = 16, height = 4 )
fig6F
dev.off()
```

